### ISSUE TITLE
Support Key queries with in Spanner repository methods

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1023]
Also, with `@Query`.

**Comment by ChengyuanZhao** [comment]
@meltsufin could you explain what you mean by this? 

The SpannerTemplate already has a read class that takes a Key. However this isn't possible for `@Query` annotated Query Methods because Spanner client lib does not allow binding `Key` to query tags. 

The available binding types are checked for in a unit test we have, and they're in `ValueBinder`

**Comment by ChengyuanZhao** [comment]
Just wanna add: `Key` isn't a column type in Spanner. It's a helper-type that combines multiple columns. If the user wanted to query by the composite key he or she can use the columns directly (and those types are all currently supported).

**Comment by meltsufin** [comment]
Oops, I meant Datastore, not Spanner. I'll create another issue and close this one.
