### ISSUE TITLE
Datastore 'IN' and 'OR' feature support

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1091]
'IN' is a feature of not part of the GQL language, however, it will be nice to have the support of this feature in query methods.

For example:

`Collection<Singer> findAllByLastNameIn(Collection<String> lastNames);`

Can be emulated as:
```
SELECT * FROM singers WHERE last_name = 'XXX'
SELECT * FROM singers WHERE last_name = 'YYY'
```

**Comment by ChengyuanZhao** [comment]
Datastore is nice in that running multiple queries isn't inefficient because the reference materials say that the queries' runtime depend on the result size, not the underlying database size. 

However, I think the part-tree naming rules allow the user to write several of these "IN" phrases. For example:
`findAllByNameInSizeIn` would resolve to
```
SELECT * FROM singers WHERE name = 'x'
SELECT * FROM singers WHERE name = 'y'
SELECT * FROM singers WHERE size = 1
SELECT * FROM singers WHERE size = 2
```
Which can result in many duplicates in the returned data if many IN-phrases are used. 

I think it would be straightforward to de-duplicate based on the Keys of the returned entities on the client side.

**Comment by meltsufin** [comment]
Our decision is to try not to implement database features in code.
