### ISSUE TITLE
Remove spring.provides files

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1108]
Spring Boot removed spring.provides files from their starters (spring-projects/spring-boot#12435), since these files are only ever used by Spring Tool suite.

There is also a similar, albeit less conclusive, discussion in spring-projects/spring-ide#251.

@artembilan @meltsufin Should we remove it?

**Comment by artembilan** [comment]
Since [commit message](https://github.com/spring-projects/spring-boot/commit/b2f34f5c20e0bab209b9e88085cd842612e7ae23) says `Remove`, then we just need to proceed with the current recommendation.

So, I'm considering this as not a question, but as an improvement.
In the end our starters should become as simple as just one POM file 😄

**Comment by meltsufin** [comment]
+1
