### ISSUE TITLE
Add saveMap and readMap to DatastoreOperations

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1138]
Need to check if it's possible at all.

**Comment by ChengyuanZhao** [comment]
```Map findByIdAsMap(Object id, TypeInformation mapType) ```

We have to use "TypeInformation" vs plain old "Class" because we need the type parameters of the key and value, and also the value type may have type parameters.
I also intentionally didn't put `Map<A,B>` as the return type and `TypeInformation<Map<A,B>>` as the param because `B` might be a type with type param like `List<Double>` or even another embedded `Map<C,D....>` , and `B` would only refer to `List` or `Map` in those cases respectively, so having these type params doesn't actually get us anything. 

`void writeMap(Object id, Map map)`
I don't think we need the type information for the write because we can examine each item in the map and convert based on their individual types.

**Comment by dmitry-s** [comment]
I think it has to be 
`Map findByIdAsMap(Key key, TypeInformation mapType)`

`void writeMap(Key key, Map map)`

Because we need to get not only an id, but also a kind, and a Key has both.
