### ISSUE TITLE
Address high-severity security vulnerabilities

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1207]
We now have Snyk that detects security vulnerabilities enabled on the repo.
Whenever it affects a direct dependency of the project, we can sometimes just upgrade, but otherwise we need to file bugs upstream to other Spring projects.
This issue is to go through the Snyk report and address all of the high-severity security vulnerabilities by either upgrading or filing bugs to upstream projects.

**Comment by elefeint** [comment]
The 2 high `ch.qos.logback:logback-classic ` vulnerabilities in three logging-related projects are false positives due to the way Snyk web parses dependencies. I sent information about this issue to Snyk; will update when they respond.

Projects:
* `spring-cloud-gcp-starter-logging`
* `spring-cloud-gcp-trace-sample`
* `spring-cloud-gcp-logging-sample`

Vulnerability: https://app.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-30208

**Comment by elefeint** [comment]
The `com.fasterxml.jackson.core:jackson-databind` vulnerabilities will be resolved when we update to spring-boot 2.2.0.BUILD-SNAPSHOT (after [Greenwich release](https://github.com/spring-cloud/spring-cloud-release/milestones)?).

spring-boot 2.2.0 is on jackson databind version 2.9.8.

**Comment by meltsufin** [comment]
Fixed by #1402
