### ISSUE TITLE
HIGH Read latencies using framework

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1221]
Query console for a query takes around 5ms

![image](https://user-images.githubusercontent.com/2513330/48443601-504a0780-e757-11e8-9fe0-37ed6594c1b5.png)

same query using framework takes around 2102 ms for the first execution and took around 50ms during the second execution.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao @meltsufin 
Can you please help ? We have clients who are asking us to get the turnaround response to hundred ms but our queries are taking way too longer when we join or data is huge.

**Comment by vineela-gampa** [comment]
This is actually for plain vanilla but join takes even long.

**Comment by meltsufin** [comment]
The first execution probably requires some resource to be created for the first time like network connections. That may explain the longer than usual initial response time. I suspect that the elapsed time reported by the console is actually query processing time, whereas when you measure the time from the application, it also includes the network round-trip from Spanner to your client application.

Also, if we believe there is a performance issue, we would need to isolate it to the framework rather than the Spanner client library that the framework delegates to. Can you run the same experiment with the [Spanner client library](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-spanner) directly and see if the performance is better than using Spring Data Spanner?

Thanks!

**Comment by vineela-gampa** [comment]
@meltsufin @ChengyuanZhao  Ran the test its almost comprable .

But a huge difference comes from using interleaved vs non interleaved.

Say for ex Tables T1 (PK1)  INTERLEAVED TO T2(PK1,PK2) (1-MANY) INTERLEAVED TO T3(PK1,PK2,PK3).

Query - SELECT * FROM T1@{FORCE_INDEX=T1_INDEX} WHERE COL1=XYZ  mapped to T1 entity

Queries being executed and the reason why spanner takes long time during interleaved nature.

1)SELECT * FROM T1@{FORCE_INDEX=T1_INDEX} WHERE COL1=XYZ - Fetched PK1

2)SELECT * FROM T2 where PK1=PK1  - Get list of PK2 (say N)

 **3) SELECT * FROM T2 where PK1=PK1  and PK2=PK2 N TIMES  - This is totally causing high READ LATENCIES.**

How are indexes  to child tables applied when queries are using interleaved nature ?

**Comment by meltsufin** [comment]
@ChengyuanZhao N+1 does look a like a serious perfromance issue. Would we be able to fetch all of the interleaved children in Step (2) rather than just their primary keys. I'm surprised to see that we're first getting the list of keys of the children and then fetching each individually. Is this what we're really doing?

**Comment by meltsufin** [comment]
Just to clarify, when we have a single parent with N interleaved children, how many queries do we run? It looks like you're saying we're running just 2 queries, not N + 1. So, that's good.

The problem might be when the interleaving goes deeper with grandchildren, and then we run a separate query for each child to get the grandchildren. I think if that's all that's going on, it's fine. I don't see a way to avoid the N + 1 issues when dealing with grandchildren.

Is this accurate?

**Comment by ChengyuanZhao** [comment]
@meltsufin yes that is exactly right :)

**Comment by meltsufin** [comment]
@vineela-gampa I would say it works as intended then. How would you recommend we improved this behavior?

**Comment by meltsufin** [comment]
How would we construct it? Are you imagining something like `select grandchildren where parent is in (list of children keys)` and then match the grandchildren to children in code?

**Comment by ChengyuanZhao** [comment]
I should also mention that grand children don't all need to be of the same type either

**Comment by vineela-gampa** [comment]
Yes I was thinking it the same as you mentioned

**Comment by vineela-gampa** [comment]
> I should also mention that grand children don't all need to be of the same type either

@ChengyuanZhao whats the usecase under which children will not be of same type ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Each pojo can have multiple interleaved child collection properties. These properties are of different types. Some child types may have multiple child types of their own. some child types might not have any child types.

**Comment by meltsufin** [comment]
@ChengyuanZhao I'm not completely following your point about grandchildren not being the same type. Don't we require the children to be of the same type and hence transitively the grandchildren to be of the same type. Of course, this only holds true for each collection in the entity.

**Comment by meltsufin** [comment]
OK, yes I see how having multiple child collections at each level could get quiet complicated. There's probably still a way to ultimately reduce the number of queries one does to fetch all of the grandchildren, but it seems rather complex to be a high priority at this point.

@vineela-gampa I would suggest to reduce your reliance on one-to-many mapping with `@Interleaved` and rather fetch children and grandchildren explicitly when needed by parent ID. Deep and complex entity hierarchies with one-to-many are generally rather inefficient. You often end up fetching a lot more data than you end up using to perform an operation.

**Comment by vineela-gampa** [comment]
@meltsufin yeah we are removing the use of interleaved on our reads. 

When are you branching ? We want to stick on to stable version.
