### ISSUE TITLE
Use Datastore Statistics queries for countAll queries

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#1248]
See https://cloud.google.com/appengine/docs/standard/java/datastore/stats

**Comment by ChengyuanZhao** [comment]
@dmitry-s @meltsufin 

FYI this looks like it needs 2 queries. The reason is that the stats in that metadata are versioned by timestamp. The documentation linked recommends getting the latest timestamp for stats from another metadata table. 

We cannot just sort by timestamp because there is no existing index for sorting on timestamp on the metadata table.

**Comment by ChengyuanZhao** [comment]
Yes I know. I was just letting you guys know so you're not surprised when you see it in the PR.

**Comment by ChengyuanZhao** [comment]
update: slight delay in this. It's a straightforward code change, but in testing i'm having trouble getting the queries on the metadata kinds to return anything. so it's still WIP

**Comment by ChengyuanZhao** [comment]
@dmitry-s , @meltsufin  In testing it looks the the metadata tables are not updated with each query. In fact it looks like there is a lag of more than a few minutes  in my experience testing. (this may explain why there is an emphasis on timestamps for these stats. they are far from strongly consistent as with our  current key-query method).

**Comment by meltsufin** [comment]
That's good to know. I think based on this discovery, we should probably drop pursuing this as a viable option for `countAll`.
