### ISSUE TITLE
Datastore , find some dynamic way to set namespace to support multi-tenant  

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1289]
I was speaking with Ray and he explained a use case based on REST repositories where the namespace (perhaps each customer is a tenant/namespace) is part of the request. 

Other than just for the REST example there could be other use cases. I've had at least one large user on Spanner asking for setting the namespace in a way that's more dynamic than just in application.properties. In spanner there isn't a namespace to set at all, but here at least there is one, so perhaps we should find a way to do it.

**Comment by pflima92** [comment]
Hi lads, I want to follow this thread. 

Currently, I'm working on a project that demands exactly what was described by @ChengyuanZhao. 

Let's start, the GCP introduces the namespace as a way to support Multitenancy (https://cloud.google.com/datastore/docs/concepts/multitenancy) and I believe that isn't the matter to be discussed here, but possibilities, scenarios, and paths that we can go to support it isn't? 

As I said I'm working on a project that needs it to provide a SaaS application, and there is not only for rest services, there is more kind of applications involved, such cloud streams (pub/sub, batchs, etc...). Since that currently the cloud-gcp doesn't provide full support for namespaces, we're implementing some customizations through the spring-cloud-datastore, isn't ideal but I was waiting for that matter be discussed, and here are us.

In my context are applied either stateful and stateless, our web approach was based on intercept a request based on a Principal provided by the spring-security and make it available using a component factory to fulfill the namespace before any DatabaseOperation be handled, it's a bit tricky and demands a series of modifications and beans redefinitions (I'm just drafting what we're doing to handle it). It's a similar approach based on the @Multitenant from eclipse link (pls, don't judge lol). Some concerns were introduced here, such the ability to work with event buses using that approach since based in a context request we'll need to propagate the namespace identifier... 

I just tried putting some thoughts on it, cause I'm really interested to follow and contribute as well... I'm looking forward to have it implemented. So, probably a lot of wtd,

**Comment by meltsufin** [comment]
@pflima92 Thanks for the input! If you have any code to share, we would be interested in seeing it.
We support Datastore namespaces as far as the [Datastore client library](https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-clients/google-cloud-datastore) that we build on supports it. AFAIK, you can only set the namespace upon creation of the `Datastore` object. So, as long as it's a singleton, there doesn't seem to be a straightforward way to change it dynamically during runtime.
One option to explore would be to not rely on the `Datastore` and its `KeyFactory` for `Key` creation (with pre-set namespace) but instead set the namespace of the `Key` based on some run-time parameter.
We may even be able to support it by accepting a SpEL expression for the namespace configuration parameter and evaluating whenever we need to create a Key or Query. @ChengyuanZhao WDYT?

**Comment by pflima92** [comment]
Hi @meltsufin , of course. I'll merge the latest release on my code and I'll share some inputs on that. But it follows your thoughts, I tried to give that responsibility to the `KeyFactory` object and it's responsible to inject the namespace, although if I not wrong, I'd issue with the dynamic queries, it's related because the core wasn't designed to do what I'm doing at moment. Will be easier to explain since I share some code..

**Comment by ChengyuanZhao** [comment]
@meltsufin @dmitry-s 

I can take this one. 

What do you guys think about the idea we discussed and agreed before for Spanner: we  accept a bean for a `NamespaceProvider` that the user can implement on his own for multi-namespace/multi-tenant use. The default bean we provide just behaves with the single namespace as we do now.

**Comment by ChengyuanZhao** [comment]
Just wanted to give some more detail about things work now and what it would look: 

-  the namespace is kept in the Datastore client object. 
-  this client object is how we execute operations AND generate new keys.  That's how we know what namespace new keys we create belong to.

As a result we need to:
- accept from the user a provider of namespace. (the thought is the user could do anything here. perhaps based on a threadlocal namespace) 


Behind the scenes: 
- in DatastoreTemplate and ObjectToKeyFactory we use Provider-of-Datastore client instead of directly using a Datastore client. 
- The actual implementation of this provider is some sort of caching thing like we use in Spanner. 
- We need to check the entire module to make sure we're not creating keys elsewhere and  missing the namespace setting somewhere

**Comment by meltsufin** [comment]
@ChengyuanZhao  What do you think of the ideas below? Do we really need multiple Datastore clients, or is it enough to control the key creation?

> One option to explore would be to not rely on the `Datastore` and its `KeyFactory` for `Key` creation (with pre-set namespace) but instead set the namespace of the `Key` based on some run-time parameter.
> We may even be able to support it by accepting a SpEL expression for the namespace configuration parameter and evaluating whenever we need to create a Key or Query.

**Comment by ChengyuanZhao** [comment]
@meltsufin We can make keys of other namespaces, but have queries and operations on whole kinds that don't involve keys, and in those cases the client just uses its configured namespace.

**Comment by meltsufin** [comment]
> @meltsufin We can make keys of other namespaces using a single client, but we have queries and operations on whole kinds that don't involve keys, and in those cases the client just uses its configured namespace (configured when building the client, that is).

Got it. So, then we kind of need to go with the approach we adopted for Spanner, where we have a `Supplier` for `DatabaseClient`.
