### ISSUE TITLE
README give better information

### ISSUE THREAD

**Issue by ludoch** [spring-cloud/spring-cloud-gcp#130]
I see in the README:
"These properties are optional and, if not specified, Spring Boot will attempt to automatically find them for you"
I would like to see why I would need to modify the default value:
Maybe when I talk to a different project for resources?
Maybe I am not on GCP?
In the case of GAE Standard, or GCE? 

If the value are good as default, then it is confusing to put in a short README doc that you can change them when you do not have to...
KISS.

**Comment by joaoandremartins** [comment]
You would need to provide credentials running outside of GCP or running locally, for example.

The real issue I see here is when I'm running locally with a certain service account configuration and then deploy to GAE or GCE and the app can't start because it obviously can't access the credentials in the file system. (Although in pure GCE, the credentials could be somewhere else in the file system...)

I might add to the README that if running on GAE or GCE, no credentials should be provided and it should be left to the Core Starter to get the correct credentials (App Identity or Metadata Server).

Having to enable/disable the `spring.cloud.gcp.credentials-location` before and after the GAE/GCE deployment is not a great user experience, but I'm not sure what we can do better here...
