### ISSUE TITLE
Configure `checkstyle` plugin to allow for builds from submodules

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#131]
Currently, `checkstyle` plugin is configured with `src/checkstyle/` path : this approach does not allow for builds from sub-modules like `google-cloud-examples`, fails on not finding the checkstyle configuration.

[This](https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html) seems like the recommended solution.

**Comment by saturnism** [comment]
it was a little annoying for me as well. I noticed we do inherit spring-cloud-build as a parent, which already applies checkstyle rules.  It appears that we have more stringent rules?

https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml

**Comment by meltsufin** [comment]
We definitely have [more stringent rules](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/src/checkstyle/checkstyle.xml) than [spring-cloud-build](https://github.com/spring-cloud/spring-cloud-build/blob/master/spring-cloud-build-tools/src/main/resources/checkstyle.xml).

I guess we can make a module like `spring-cloud-gcp-tools` which will house it and follow the pattern of `spring-cloud-build` with its [spring-cloud-butild-tools](https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L269).

Alternatively, we can just contribute our `checkstyle.xml` to `spring-cloud-butild-tools` and call it something like `checkstyle-strict.xml` so that we don't break other projects. (This is my preference.)

**Comment by joaoandremartins** [comment]
Inheriting alone from `spring-cloud-build` doesn't apply checkstyle rules. I think we'd need to add `spring-cloud-build` as a dependency to `maven-checkstyle-plugin`, as recommended [here](https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html). Also, it appears that `spring-cloud-build` only started having build rules since 1.3.5, which is still SNAPSHOT...

Mike, I'm not sure if what you're suggesting is possible. I suspect you can only have a single `configLocation` element under `maven-checkstyle-plugin`'s `configuration`.

I think we should create a spring-cloud-gcp-build-tools sub-module for now and add checkstyle there. It can be a stopgap solution if we're thinking of asking Spring to add the other rules to their checkstyle.xml, but that might not happen at all... (Maybe good candidate for spring-cloud-build 2.0.0 GA?)

**Comment by joaoandremartins** [comment]
Nvm about the single location issue, I see how each "client" can specify different checkstyle files now...
