### ISSUE TITLE
spring-cloud-gcp-starter-config 1.1.0.RELEASE is missing

### ISSUE THREAD

**Issue by samhalpa** [spring-cloud/spring-cloud-gcp#1401]
Is spring-cloud-gcp-starter-config 1.1.0.RELEASE is available in spring-cloud-gcp-dependencies-1.1.0.RELEASE in maven central. I guess it is not.
See: [spring-cloud-gcp-dependencies](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-gcp-dependencies/1.1.0.RELEASE)

and

[spring-cloud-gcp-starter-config](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-gcp-starter-config?repo=springio-plugins-release)

**Comment by elefeint** [comment]
You are correct. Config starter is not in the GA release because the underlying [Runtime Configuration API ](https://cloud.google.com/deployment-manager/runtime-configurator/) is still technically in beta.

**Comment by mbenson** [comment]
What was the actual resolution of this issue? `spring-cloud-gcp-starter-config`  is configured to skip deploy, but `spring-cloud-gcp-config`, also mentioned in `spring-cloud-gcp-dependencies`, doesn't even seem to exist.

**Comment by meltsufin** [comment]
Right, `spring-cloud-gcp-starter-config` is not in the released versions because it's not GA, and the reason it's not GA is that the underlying [Runtime Config API is Beta](https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest).

Check out the new [Spring Cloud Bus](https://cloud.spring.io/spring-cloud-gcp/spring-cloud-gcp.html#_spring_cloud_bus) support, that you can use as an alternative for configuration management.

Regarding `spring-cloud-gcp-logging`, it not in the 1.1.x release tag because it has only been added as a module in 1.2, which hasn't been released yet outside of snapshots.
