### ISSUE TITLE
Allow customization of Spring Integration objects used in Spring Cloud Stream

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1432]
We don't seem to give Spring Cloud Stream client apps much ability to configure `PubSubInboundChannelAdapter` or `PubSubMessageSource`, since `PubSubMessageChannelBinder` directly instantiates both in its own code. 

Both `PubSubInboundChannelAdapter`  and `PubSubMessageSource` would benefit from ability to customize `headerMapper` and `payloadType`.

 `PubSubMessageSource` also needs to allow customization of `maxFetchSize` -- in Spring Cloud Stream integration, it would give better performance to pull a batch over the network, and then stream it internally within the app.

The simplest way to implement the properties is by adding them to `PubSubConsumerProperties`.

**Comment by artembilan** [comment]
Note: the `payloadType` for Spring Cloud Stream must always be `byte[]`. The Spring Cloud Stream is responsible for proper conversion from `byte[]`.

The `headerMapper` cannot be configured via properties since it has to be a bean.
We could provide some default one and allow end-user to override it with his/her own preferences. But again: do we really need to do that, unless just map everything we receive from Pub/Sub. 
We talk about Spring Cloud Stream which has its own strong opinion.

We definitely can provide a hook to configure a `maxFetchSize` though. 

Need also to dig for more properties if that...

**Comment by elefeint** [comment]
Ah, so only `maxFetchSize` is reasonable. That should be easy then!
