### ISSUE TITLE
Look into supporting CreatedBy and CreatedDate audit in Spanner

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1456]
There needs to be some work creating a custom IsNewStrategy for Spanner. 

To detect if an entity is just-created:
- a "version" column could be our server-side commit-timestamp column. 
- However, unless we provide auto-generated ID values (which is a separate issue), we won't be able to see a "null" key because we simply don't allow it.

**Comment by meltsufin** [comment]
As noted by Mark, please use Mongo implementation as a reference.

**Comment by meltsufin** [comment]
How do other modules handle the case where the user specifies the id of a new entity instead of relying on id generation? @mp911de

**Comment by mp911de** [comment]
Spring Data abstracts this under [`IsNewStrategy`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/support/IsNewStrategy.html). Entities can either implement [`Persistable`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Persistable.html) or be versioned/use optimistic locking (see [`@Version`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/annotation/Version.html)). 

Without further hints, we consider entities with an `@Id` not `null` as an existing entity.

When using auditing, typically we either use events or `EntityCallbacks` (new since Moore RC1) to invoke [`AuditingHandler`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/auditing/AuditingHandler.html) or `IsNewAwareAuditingHandler`.

**Comment by ChengyuanZhao** [comment]
Thank you Mark for that explanation. It's as we saw back in February, the default checking is 

```
	/* 
	 * (non-Javadoc)
	 * @see org.springframework.data.support.IsNewStrategy#isNew(java.lang.Object)
	 */
	@Override
	public boolean isNew(Object entity) {

		Object value = valueLookup.apply(entity);

		if (value == null) {
			return true;
		}

		if (valueType != null && !valueType.isPrimitive()) {
			return value == null;
		}

		if (Number.class.isInstance(value)) {
			return ((Number) value).longValue() == 0;
		}

		throw new IllegalArgumentException(
				String.format("Could not determine whether %s is new! Unsupported identifier or version property!", entity));
	}
```


This won't apply to Spanner because 
- we can't generate IDs , so the ID can't be null 
- 0 value numeric IDs being "new" isn't appealing to us because 0 is a valid value for a key for Spanner, and it is also a very narrow use-case considering we see many of our customers using multi-column keys. 

I can't think of any other way to do this locally (meaning not  querying Spanner to check if the id exists), and I am pretty sure the team isn't for that idea.

I think the best choice here is to close this as an unsupported feature. But of course, we can always reopen if users let us know they want it.
