### ISSUE TITLE
Inheritance hierarchy for a single kind

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1475]
Is it possible to support inheritance strategy for a single kind which containing entities for two or more different classes in an inheritance hierarchy?

For example, we have types:
```

public class Shape {    
    private String id;
    //other fields
}

public class Circle extends Shape {}

public class Polygon extends Shape{}

```
I would like to get information about all the shapes which was saved.

```
var circe = new Circle();
var polygon = new Polygon();
shapeRepository.save(circle);
shapeRepository.save(polygon);
var shapes = shapeRepository.findAll();

```

Right now I receive a collection with 2 elements of 'Shape' type. Is it possible to add mechanisms, for example like [JPA discriminators](https://docs.oracle.com/javaee/7/api/javax/persistence/DiscriminatorColumn.html), which will make childs (which are in an inheritance hierarchy) into their real types?

**Comment by ChengyuanZhao** [comment]
If my reading of the JPA discriminators feature is correct this means:
- entities of all 3 types (shape, polygon, circle) are stored in the SAME table
- entities of the 3 types are distinguished by a "DTYPE" column that is invisible to the user, but tells Spring Data which java type it should correspond to

I think this would be a pretty deep change to the module that touches many many parts. 

Furthermore, I think it's somewhat contrary to the idea that each java type gets its own table and how each java type gets its own repository. My opinion and recommendation is to not support this feature, and to recommend users to use separate repositories for the specific types they want retrieved. 

WDYT @dmitry-s @meltsufin

**Comment by meltsufin** [comment]
@sergeymeshkov Can you just use a separate entity and repository for each type? You should still be able to map all of them to the same kind.

**Comment by ChengyuanZhao** [comment]
@meltsufin I'm not sure that would work as expected  because you may be retrieving rows for other types and you wouldn't be able to tell. (especially if using the count() or findAllI() methods).

**Comment by meltsufin** [comment]
Right, the burden of ensuring that would be on the user. It's not as good as what JPA provides, but an imperfect workaround.

**Comment by sergeymeshkov** [comment]
I totally understand that this feature is complicated, however, if the Spring Data Datastore will not support this feature, a large number of use cases will be lost. I am not sure that the idea that every type should have a separate repository (if we talking about inheritance hierarchy) is a good one because most of the devs which use Spring Data also use Java (mostly), which support inheritance and a lot of developers use it quite often. We also use this feature in our project, but right now we can't migrate to Datastore, because the framework doesn't support this feature and code refactoring will require a lot of time. Moreover, even MongoDB (NoSQL database) support inheritance (with _class field) feature in Spring Data MongoDB.
Let's me provide you another example which shows existing limitation.

For example, we have hierarchy:
```
interface Detectable {
  boolean isDetectable();
}

abstract class Transport  implements Detectable {}

class Boat extends Transport {
 BoatType type;
 boolean isDetectable() {
    return type = BoatType.SMALL;
  }
} 

class Car extends Transport {
 CarBrand brand; 
 boolean isDetectable() {
    return type = CarBrand.TESLA || CarBrand.FORD;
  }
}

class User {
 @Reference
 Collection<Transport> transports;
}

```
In this case, logic for checking detectable transports will look like this:
```

var isUserHaveDetectableTransports = userRepository
.findById(12345)
.getTransports()
.stream()
.anyMatch(transport -> transport.isDetectable())
```

Such code is not possible in case we storing everything in different entities. In the current implementation it might look like this:

```
//datastore entity
class User {
Map<TransportType, Long> transports;
}

//dto
class UserAggregation {
Collection<Transport> transports;
}

var userTransports = userRepository
.findById(12345)
.getTransports();

Collection<Transport> transports = loadUserTransports(userTransports);
```

Then we have to load transport from a separate repository based on transport type and create new user aggregation. This solution is not developer friendly. Also, it will create n + 1 queries, because we load transport for every type from the separate repository (from my understanding, even if we use findByIds, 1 call of findByIds = n call of findById).

Thus, I believe that this feature would be very useful.

**Comment by meltsufin** [comment]
@sergeymeshkov Thanks for the in-depth discussion. I don't think we're arguing whether this feature is useful. It certainly is. The fact that Spring Data MongoDB supports it is also a nice reinforcement of its utility. We were more trying to address a way to work around the absence of this feature for the time being.

@ChengyuanZhao @dmitry-s Can you please do a bit more investigation on what it would take to implement this feature, referencing the MongoDB implementation?

**Comment by dmitry-s** [comment]
I think we can add support for this, doesn't look like it will take a lot of effort.

**Comment by ChengyuanZhao** [comment]
@dmitry-s I think this might not be so simple...

Some considerations if rows of several different java types live together in one table:

1. count() and exists() and such functions will need to be aware of the DTYPE column
2. all of our generated query methods will need to append additional DTYPE column conditions.
3. appending the additional DTYPE column condition may involve messing with query strings depending on aggregation of the Query Method or if it's provided via GQL annotation
4. key collisions may arise because two objects with same ID values now share the same Kind/table whereas they could be fine in separate kinds/tables


@meltsufin FYI

**Comment by dmitry-s** [comment]
@ChengyuanZhao 
I was thinking about restricting those child classes to not having their own repositories. In that case most of the issues would be resolved. They all the child classes would have to inherit the id column from the parent.

**Comment by ChengyuanZhao** [comment]
@dmitry-s In this example would that mean disallowing `DatastoreRepository<Car>` and ``DatastoreRepository<Boat>` and ONLY allowing `DatastoreRepository<Transport>` ? 

That seems like we're throwing away a lot of functionality.. since the interesting properties and fields all exist in the subclasses that users would want to use Query Methods on `findByBrandWheelsizeOrderByPaint` and `findByWeightLengthOrderbyPropellers` would only be meaningful on the disallowed Car and Boat repos. Furthermore, for users to actually get Car and Boat objects would they need to do reflection on their own from `List<Transport>` ?

**Comment by meltsufin** [comment]
We have a wonderful benefit of an existing implementation for MongoDB that we can reference to answer some of these questions. Which of these consideration is a deal-breaker or extremely disruptive to the current design? On the surface, it seems that we can make all of it work.

**Comment by ChengyuanZhao** [comment]
@meltsufin the dealbreaker is that adding the `_class` or `DTYPE` column as a condition to any and all queries means there must be a composite index including that column and whatever else columns appear in the query.

**Comment by dmitry-s** [comment]
Another option is we could just limit children repositories.

**Comment by ChengyuanZhao** [comment]
@dmitry-s  But isn't that kind of like throwing your wallet in the trash so you don't have to worry about your wallet getting stolen

**Comment by dmitry-s** [comment]
@ChengyuanZhao it is not, because it would still provide some useful functionality

**Comment by ChengyuanZhao** [comment]
After some discussion here some points about how we'll be implementing this:

- The JPA discriminator approach where with explicit user-visible column and discriminator value seems more appropriate than the `__class` column that holds a fully-qualified java class name that SD MongoDB and Cassandra use.  So we will be reusing the JPA discriminatorcolumn and discriminatorvalue annotations 
- For all queries other than user-provided-GQL queries we will append an extra condition on that discrim column
- It will be the user's responsibility to manually create any composite indexes to make take advantage of that column if they're using a child-class repo
- For user -provided GQL queries we will throw an error in our first implementation because it's not clear how to add that extra condition into the query.  (unless that extra condition can be added builder-style)

**Comment by ChengyuanZhao** [comment]
I think it makes sense to break this up into these parts so we have PRs of manageable size:

- [ ] PersistentEntity and PersistentProperty. modifications so that get table name on child tables returns the parent table's name - **Chengyuan**
- [ ] Template changes to read the extra column when mapping and choosing the appropriate class/type
- [ ] Query Methods. either throwing error when appropriate or appending the condition 
- [ ] Ref doc and sample

@dmitry-s I think maybe we could break it up like this. I'll take that first one
