### ISSUE TITLE
Spanner transactions - aborted exception - how to specify retryDelay or catch abortedException to replay what we intend to do

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1520]
Hi @ChengyuanZhao @meltsufin 

Below is the chunk of code we have to handle the issue opened earlier. https://github.com/spring-cloud/spring-cloud-gcp/issues/1377

Currenlty what we have observed is 2 THREADS (T1 / T2) are entering the readwriteTransactionBlock at the same time. Both are reading  below line from the fullcode snippet at the same time. 

`Entity latestentity = spannerTemplate.read(entity.class, Key.newBuilder()
					        .append(PK).build());` - Amount on ths entity - **$90.0**

Entity ( **$90.0**)for T1 which got updated with new values say E1 (**amount updated to 90 (old) + 100 **) has lastUpdated == latestEntity.

Entity for T2 which got updated with new values say E2 (**amount updated to 90 (old) - 100 **)  has lastUpdated == latestEntity.

we expect after transactions are done for the db updated entity to have 90 $ as (Transaction T1 added 100$ to original , T2 negated 100$) but apparently spanner is holding -10 (which is the last transaction value). 

I observed that spanner is throwing aborted exception bcoz both the threads are modifying the same row and same column. Is there a way to increase teh retryDelay to 1s rather than nanoseconds ?
I observed there is a countdownlatch(1) - where spanner will retry once before calling it off ?

**Is there a way to avoid doing a value ovveride apart from using the locks** ?Transactions are supposed to serve the same thign but due to narrowing the locking to a specific column we are hitting this roadblock. Please advise on whats recommended. @ChengyuanZhao @meltsufin 

`Caused by: io.grpc.StatusRuntimeException: ABORTED: Deadlock with higher priority transaction.
retry_delay {
  nanos: 29992054
}

	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 27 common frames omitted

2019-03-12 00:28:35.853DEBUG [] [         Gax-25] c.g.cloud.spanner.TransactionRunner      Commit aborted

com.google.cloud.spanner.AbortedException: ABORTED: com.google.api.gax.rpc.AbortedException: io.grpc.StatusRuntimeException: ABORTED: Deadlock with higher priority transaction.
retry_delay {
  nanos: 29992054
}

	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:117)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80)
	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.get(GapicSpannerRpc.java:558)
	a`

`1 ) boolean retVal = dao.performReadWriteTransaction(spannerTemplate -> {
				
2)				for (Entity entity : entityList) {
3)					former.transformMembershipTierAuditEntity(entity,
4)					        LoyaltyServiceConstants.TIER_CHANGE_REASON_MET_THRESHOLD);
5)					Entity latestentity = spannerTemplate.read(entity.class, Key.newBuilder()
6)					        .append(PK).build());
7)					log.info("latestentity read at {} is -- {}", Timestamp.now(), latestentity);
					if (latestentity == null) {
						
8)						spannerTemplate.insert(entity);
						
9)					} else if (latestentity.getLastUpdated().compareTo(entity.getLastUpdated()) == 0) {
10)						entity.setLastUpdated(Timestamp.now());
						
11)						spannerTemplate.update(entity, entity.getUpdateColumnNames());
					
12)					} else {
						// return false back to service as the entity got updated by another thread
						log.info(
						        "Retry again as the entity got changed");
13)						return false;
					}
					
					
					
				}
				
14)				return true;
			});
		
			return retVal;
			
		} catch (com.google.api.gax.rpc.AbortedException ae) {
			return false;
		} catch (SpannerException ex) {
			
			--
	}`

**Comment by ChengyuanZhao** [comment]
@vineela-gampa taking a look now

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Configuring the grpc to retry is not a setting the client lib exposes in its `SpannerOptions` class. (I'm not sure if using the low level spanner-agnostic grpc retry was the intended way to handle retries for this very-spanner-specific situation)

Otherwise I think you would need to retry running the anonymous function for the thread that read the row second. 

Take a look at this https://cloud.google.com/spanner/docs/transactions#read-write_transactions 
The section called "Isolation" describes the rules regarding separate transactions touching the same row at the same time. The transaction that read a given row second is not allowed to commit if it read that row while the earlier transaction that read that same row hadn't ended. This sounds consistent with what you're describing. 

Just FYI,  the case where you would see the changes of a concurrent transaction that commits earlier inside another transaction is only if this other transaction hadn't tried to read those specific rows yet ( https://cloud.google.com/spanner/docs/transactions#rw_transaction_semantics )

**Comment by meltsufin** [comment]
@vineela-gampa Since you are working inside a read-write transaction, I would imagine that if one of the transactions is aborted, it's before it even gets a chance to read the value, because another transaction would be holding a read-write lock on it. Are you sure that the transaction is aborted after the reads and you apply the calculations to both?
If I understand you correctly, you would like the transaction to wait for the lock a little longer than the default.

**Comment by meltsufin** [comment]
@vineela-gampa Since you are working inside a read-write transaction, I would imagine that if one of the transactions is aborted, it's before it even gets a chance to read the value, because another transaction would be holding a read-write lock on it. Are you sure that the transaction is aborted after the reads and you apply the calculations to both?
If I understand you correctly, you would like the transaction to wait for the lock a little longer than the default

**Comment by meltsufin** [comment]
@vineela-gampa Since you are working inside a read-write transaction, I would imagine that if one of the transactions is aborted, it's before it even gets a chance to read the value, because another transaction would be holding a read-write lock on it. Are you sure that the transaction is aborted after the reads and you apply the calculations to both?
If I understand you correctly, you would like the transaction to wait for the lock a little longer than the default.

**Comment by ChengyuanZhao** [comment]
Closing the issue: The behavior here is expected. The user application must handle situations of competing transactions for the same keys/rows.
