### ISSUE TITLE
SpannerTemplate support choosing among multiple connections/instances

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1525]
There are a few steps planned below that go from more-general support to more and more specific features: 

1. `SpannerTemplate` to use a very general so-called `DatabaseClientProvider` bean. The user can implement and provide a bean of this interface in Spring config. This interface would provide various database client / database connections for each request. 
2. provide an  implementation of `DatabaseClientProvider` that reuses all of the other Spanner connection auto-config settings and only varies in the instance-id. 
3. expand the `DatabaseClientProvider` interface to accept `ApplicationEvent` (which we already publish for all operations (if I recall)) so that the instance selection for each request can now see the specifics of the each operation

**Comment by meltsufin** [comment]
(Sorry, closed by mistake.)

During our design discussion, we talked about (3), and I thought the concensus was that we should hold off attempting to address that since there are some issues with the idea.
- What we already implemented in #1530 addresses the original user's request.
- Even if one is able to partition the data on write, it's essentially impossible to do on the read. This point is especially important. I think it makes the whole idea of multiplexing instances based on row content impossible with this approach.

**Comment by ChengyuanZhao** [comment]
@meltsufin  

I don't think the concerns you refer to are actually issues anymore!

The reason is that the user can selectively override the functions he wants. 

For example. 

If he overrides the upsert and read-by-key methods, then he can choose the database client by the entity value. 

However, if he wants to query and submit string queries then he still use the databaseId provider config in the same application! He simply didn't need to override the query method using this method.

BOTH methods can be used at the same time!

**Comment by meltsufin** [comment]
@ChengyuanZhao Can this be closed now, and the PR?
