### ISSUE TITLE
Firestore Native Mode (non-Datastore mode) support 

### ISSUE THREAD

**Issue by nbrinks** [spring-cloud/spring-cloud-gcp#1534]
I saw #1507 but wasn't sure why it was closed.
Are there any plans at this time to add native Firestore support?

**Comment by meltsufin** [comment]
I think the OP closed #1507 because they were looking for Firestore support in Datastore mode, which we already have.
Yes, we're planning to support Firestore, but we can't share any concrete timeline right now.

For others reading it, 👍 up this issue if you're interested in Spring Data Firestore support.

**Comment by meltsufin** [comment]
The Spring Data support for Firestore has been added in 1.2.0. Please create new issues based on testing of the new features.
