### ISSUE TITLE
New ID column created in Datastore Entity

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1677]
From @naveenreddyalka via Gitter:

> Hi All, I am working on Google DataStore with Spring Data. My problem here is, when with out spring data if we use core datastore client and we could create an entity with a key which is not a property/field - basically when we move to Spring Data, create an `@Entity` class and mark a id field with `@id` then its being used properly for the key but also a new 'id' property is created - now the question is can we have an id field in the entity with out it being created as a new property in google datastore with spring data

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao PTAL

**Comment by ChengyuanZhao** [comment]
@naveenreddyalka Just to clarify, when you create these new java entity instances are you leaving the ID property null / unset?

**Comment by ChengyuanZhao** [comment]
@naveenreddyalka

I think I know why this is happening. The reason is in Spring Data you must choose one of your properties in your Java object to be the `Id`. If your entity in Datastore previously did not a column that held the same value as the Key for that entity, then it must show up in Spring Data as a property. When that property is then saved back to Datastore it will be saved as that new ID column. In Spring Data all properties become columns, even ones marked as `@Id`.

**Comment by meltsufin** [comment]
The question is whether we should be storing the key of the entity in column at all and have this effectively duplicate storage of entity key as key and column, with a potential of them getting out of sync.

**Comment by ChengyuanZhao** [comment]
@meltsufin  that's starting to sound better to me the more i think about it. I'll think some more to see if it doesn't cause any issues and it would probably worthwhile to implement (not too huge a change actually).

**Comment by naveenreddyalka** [comment]
@ChengyuanZhao : Yes , we will be setting a string key in our code

**Comment by naveenreddyalka** [comment]
@meltsufin @ChengyuanZhao : And yes the main problem is now same value is there two times 
one as a key and then other as another property called 'key'
