### ISSUE TITLE
Annotated GQL Query Method has 2 tags but a different number of parameter values

### ISSUE THREAD

**Issue by olgmaks** [spring-cloud/spring-cloud-gcp#1680]
{"timestamp":"2019-05-13T07:02:09.618+0000","status":500,"error":"Internal Server Error","message":"Annotated GQL Query Method findAllArticlesIdsForAuthor has 2 tags but a different number of parameter values: 1","path":"/articles/ids"}

**Comment by olgmaks** [comment]
mavenBom 'org.springframework.cloud:spring-cloud-gcp-dependencies:1.1.1.RELEASE'

**Comment by olgmaks** [comment]
public interface ArticlesRepository extends DatastoreRepository <Article, Long> {

    List<Article> findArticleById(Long id);

    @Query("select id, name, description from articles where author = @author")
    List<Article> findArticlesByAuthor(@Param("author") Key author);

    @Query("select id from articles")
    List<Long> findAllArticlesIds();

    @Query("select id from articles where author = @author")
    Iterable<Long> findAllArticlesIdsForAuthor(@Param("author") Key author);

    @Query("select id, name, description from articles")
    Iterable<Article> findAllArticles();
}

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao PTAL

**Comment by ChengyuanZhao** [comment]
@olgmaks Would you happen to be using this repository class query method from multiple threads at the same time?

**Comment by olgmaks** [comment]
@ChengyuanZhao yes. when bean scope=singleton and send many request the same time

**Comment by dmitry-s** [comment]
I could not replicate the issue on the latest version. Looks like this issue was fixed there.

**Comment by ChengyuanZhao** [comment]
@olgmaks  , could you give 1.2.0.BUILD-SNAPSHOT a try?

I think this may be the same issue as https://github.com/spring-cloud/spring-cloud-gcp/issues/1610 .

What's happening is that we count the number of tags in the queries on first-use and there's like a singleton query method, so it gets counted multiple times. 

We have this fixed in 1.2.0.BUILD-SNAPSHOT, but haven't ported it back to 1.1.x because it involved somewhat extensive rewriting of the query method class.



@meltsufin  (FYI the Spanner module does it a different way and didn't have this problem)

**Comment by ChengyuanZhao** [comment]
@olgmaks 

I've merged the fix into the 1.1.x branch. It will appear in next releases of both 1.1 and 1.2 branches (we release with the Spring "release train") , but is also available in the BUILD-SNAPSHOT versions.
