### ISSUE TITLE
Spring Boot 2.2.0.M3 and Trace Starter fails to start

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1685]
Application failed to start w/ Spring Boot 2.2.0.M3, Hoxton.BUILD-SNAPSHOT, and `spring-cloud-gcp-starter-trace`.

For unknown reason, as soon as I added the trace starter, GcpConfigP'roperties is being initialized.

```
Caused by: java.lang.NullPointerException
    at org.springframework.cloud.gcp.autoconfigure.config.GcpConfigProperties.<init> (GcpConfigProperties.java:75)
```

Looking into the initialization logic:
```
public GcpConfigProperties(Environment environment) {
	if (this.profile == null) {
		String[] profiles = environment.getActiveProfiles();  // <-- fails here
		if (profiles.length == 0) {
			profiles = environment.getDefaultProfiles();
		}

		if (profiles.length > 0) {
			this.profile = profiles[profiles.length - 1];
		}
		else {
			this.profile = "default";
		}
	}
}
```

A couple of issues:
1. Not sure why this initialization is taking place when added `trace` starter.
1. `environment` appears to be null
1. `this.profile` will probably always be null, since it's the only constructor, and profile attribute won't be set until after construction.

**Comment by meltsufin** [comment]
This probably has something to do with config running during bootstrap, but why would `GcpConfigProperties` be even initialized since `GcpConfigBootstrapConfiguration` is disabled by default.
Have you tried disabling explicitly by setting `spring.cloud.gcp.config.enabled=false`?
I'm not able to reproduce with our Trace sample though.

My best guess would be that it's a regression in Spring Boot.

**Comment by Numbernick** [comment]
I'm having the same issue with Spring Boot 2.2.0.M2/M3 and GCP Storage (Greenwich.SR1). We need the spring-cloud-gcp-starter-storage so it should be ok to load the properties. But I don't see a reason why the environment is null.

**Comment by meltsufin** [comment]
@Numbernick Would you be able to share a simple app that reproduces this? Thanks!

**Comment by hongfei-zhou** [comment]
Got the same issue here after adding the trace dependency.
The `spring.cloud.gcp.config.enabled=false` is not working for me.

**Comment by meltsufin** [comment]
I'm able to reproduce with Spring Boot `2.2.0.M4` and `Greenwich.SR1` and `Hoxton.BUILD-SNAPSHOT`.
Note that everything seems to work with `Hoxton.M1`.

**Comment by meltsufin** [comment]
Possibly related to this: https://github.com/spring-cloud/spring-cloud-gcp/pull/1516

**Comment by meltsufin** [comment]
@Numbernick I think it's invalid to expect `Greenwich` release train to work with SB 2.2, since it's designed to be compatible with SB 2.1.

That being said, Hoxton should work, but it doesn't because the release train has the old version of Spring Cloud GCP in it. It brings in 1.1 instead of the current 1.2.

You can temporarily work around the issue by explicitly importing the latest version of Spring Cloud GCP by modifying the `dependencyManagement` section:

```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>1.2.0.BUILD-SNAPSHOT</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```
This should fix it permanently though: https://github.com/spring-cloud/spring-cloud-release/pull/169.

**Comment by spencergibb** [comment]
It is invalid to expect Greenwich to support boot 2.2.x
