### ISSUE TITLE
spring.cloud.gcp.credentials.location doesn't get pickup on runtime

### ISSUE THREAD

**Issue by alonsoir** [spring-cloud/spring-cloud-gcp#1733]
Hi, i have tried to configure this property using an absolut path (/Users/aironman/Downloads/TrapeDependency-dd274d8ceb38.json), a relative path (PROJECT_FOLDER/src/main/resources/TrapeDependency-dd274d8ceb38.json), another relative path (PROJECT_FOLDER/TrapeDependency-dd274d8ceb38.json), copying the json file into the static folder and I am getting a [FileNotFoundException](https://pastebin.com/VdKy6ZkF). 

I don't understand because if I [run jar tf](https://pastebin.com/qyaK1v9c), I can see that the file is included in the folder, in this case, the file is included in /BOOT-INF/classes/static folder, but FileNotFoundException. It frustrates me. Can anybody help me?

spring.cloud.gcp.credentials.location=/Users/aironman/Downloads/TrapeDependency-dd274d8ceb38.json

spring.cloud.gcp.credentials.location=/src/main/resources/TrapeDependency-dd274d8ceb38.json

spring.cloud.gcp.credentials.location=/TrapeDependency-dd274d8ceb38.json

spring.cloud.gcp.credentials.location=/BOOT-INF/classes/static/TrapeDependency-dd274d8ceb38.json

**Comment by meltsufin** [comment]
If you are using a filesystem location, you have to prefix it with `file:`. For location on the classpath, use `classpath:`.
See [docs](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M1/#_credentials).
Try this:
`spring.cloud.gcp.credentials.location=file:/Users/aironman/Downloads/TrapeDependency-dd274d8ceb38.json`.

Please let us know if this resolved your issue.

**Comment by alonsoir** [comment]
Yes, it is working, thank you @meltsufin

**Comment by falk-stefan** [comment]
@meltsufin 

Am I doing this wrong somehow?

```
spring.cloud.gcp.project-id=project-name
spring.cloud.gcp.credentials.location=file:/home/sfalk/workspaces/project-name/credentials.json
```
If I set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to the above path it is working, however, it is not if I use the setting in this `application-clients.properties` (a config for generating clients).

I am using:

```groovy
implementation 'org.springframework.cloud:spring-cloud-starter-config:2.2.6.RELEASE'
implementation 'org.springframework.cloud:spring-cloud-gcp-starter-secretmanager:1.2.6.RELEASE'
```

**Comment by meltsufin** [comment]
You might need to use
```properties
spring.cloud.gcp.secretmanager.credentials.location=file:/home/sfalk/workspaces/project-name/credentials.json
```
cc/ @dzou

**Comment by dzou** [comment]
@falk-stefan - Hey, another reason I think it's not working is that you'll have to put those settings in a `bootstrap.properties` file; see https://docs.spring.io/spring-cloud-gcp/docs/1.2.6.RELEASE/reference/html/#configuration-10

This is because the secrets are loaded during the Spring bootstrap phase of the application loading; which is a special phase of application loading defined by Spring Context.

The `bootstrap.properties` file is placed in the same directory as the `application.properties` file; in your `resources/` dir.

**Comment by YuriiYaknytsia** [comment]
I also got troubles with auth_key.json location. The problem is that my file locates in resources folder and I use this properties:
spring.cloud.gcp.credentials.location: 'classpath:auth_key.json', but when I build my project into jar file spring can't read this file with such stack-trace:
`java.io.FileNotFoundException: class path resource [auth_key.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/app.jar!/BOOT-INF/classes!/auth_key.json  	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217)`
so spring can't read file inside jar

**Comment by meltsufin** [comment]
@YuriiYaknytsia Please open an issue in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues.
