### ISSUE TITLE
Call AsyncReporter.check() when creating stackdriver beans

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1786]
spring-cloud-gcp does not rely on `spring-cloud-sleuth-zipkin` (historical reasons?), so after openzipkin/zipkin-gcp#131 is done, we'll have to implement our own version of spring-cloud/spring-cloud-sleuth#1411 when instantiating the [reporter bean](https://github.com/spring-cloud/spring-cloud-gcp/blob/2d33d096546cdf935c3ac3e5e701a9f167f2ef2a/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L138)

Longer discussion is -- should we rely on `spring-cloud-sleuth-zipkin` in the first place?

This is blocked on #1862.

**Comment by meltsufin** [comment]
We don't use `spring-cloud-sleuth-zipkin` because its purpose is to provide a reporter for the Zipkin Server. We instead create a reporter for Stackdriver Trace.
You're right that we will have to implement a check on bean creation in our own `StackdriverTraceAutoConfiguration` similar to https://github.com/spring-cloud/spring-cloud-sleuth/pull/1413.

**Comment by dzou** [comment]
See https://github.com/spring-cloud/spring-cloud-sleuth/issues/1411
