### ISSUE TITLE
Storage: Reload credentials provided by environment variable

### ISSUE THREAD

**Issue by jan-schumacher** [spring-cloud/spring-cloud-gcp#1830]
This is more a question then a bug: I wonder if it is possible to hot reload credentials at runtime and how to make it possible to do so? 
We're using vault to auto generate service account keys and to auto invalidate them after a certain amount of time. The connection stays alive for a while (don't know how long) when the credentials are invalidated.

**Comment by elefeint** [comment]
The fast answer is:  by using `@RefreshScope` from `spring-cloud-context`. I've modified our [`spring-cloud-gcp-storage-resource-sample`](https://github.com/spring-cloud/spring-cloud-gcp/blob/refreshable-credentials/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/src/main/java/com/example/GcsApplication.java) on `refreshable-credentials` branch to show how to inject a bean that will get reloaded at most every 10 seconds (it's actually whenever storage is used after the 10 second expiration, since refresh scoped beans are lazily loaded).

The more proper-in-production answer is: by still using `@RefreshScope` annotation, but in combination with [Spring Cloud Config](https://spring.io/projects/spring-cloud-config), which targets the exact usecase of reloading configuration at runtime, and seems to support [Vault](https://cloud.spring.io/spring-cloud-config/reference/html/#_vault).

**Comment by jan-schumacher** [comment]
@elefeint Thanks allot mate! `this.refresh.refresh("scopedTarget.refreshableCredentials");` Thats a nice one, didn't know about that capability! I will try it out by myself :)

**Comment by elefeint** [comment]
Use the real bean name; the "scopedTarget" prefix is just a Spring implementation detail to differentiate the scoped real bean from the proxy bean. Spring will [add it automatically](https://github.com/spring-cloud/spring-cloud-commons/blob/c76e026c196d236de9a1b1e3d19be6c170ab173a/spring-cloud-context/src/main/java/org/springframework/cloud/context/scope/refresh/RefreshScope.java#L145).

I've updated the branch:
```
this.refresh.refresh("refreshableCredentials");
```
