### ISSUE TITLE
Some Spanner integration test is not cleaning up data

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1865]
`org.springframework.cloud.gcp.data.spanner.core.it.SpannerTemplateIntegrationTests` runs fine by itself, but fails locally when all tests in ` spring-cloud-gcp-data-spanner` run. I assume it succeeds on Travis because test order there ends up different.

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao PTAL

**Comment by ChengyuanZhao** [comment]
Hmmm I'm not able to recreate. I'm running `./mvnw clean install -am --projects=spring-cloud-gcp-data-spanner -Dit.spanner=true` and running all the tests and it builds for me. 

The tables the integration tests use have SpEL in the names that translates to a timestamp, so there shouldn't be a concern about cleanup since a new table is created every time. 

@elefeint how are you running these tests?

**Comment by elefeint** [comment]
It was
```
mvn clean test -Dit.spanner=true -Dtest.integration.spanner.instance=[AN-INSTANCE] -f spring-cloud-gcp-data-spanner
```
But here is a targeted command that reproduces: 
```
mvn clean test -Dit.spanner=true -Dtest.integration.spanner.instance=[AN-INSTANCE] -f spring-cloud-gcp-data-spanner -Dtest=ParallelSpannerRepositoryIntegrationTests,SpannerTemplateIntegrationTests
```

**Comment by ChengyuanZhao** [comment]
unable to reproduce :/ If the linked PR fixes your issue then that's a pure win  :D
