### ISSUE TITLE
Replace the official Pub/Sub driver with reactor-pubsub

### ISSUE THREAD

**Issue by vy** [spring-cloud/spring-cloud-gcp#1969]
The official Google Cloud Pub/Sub driver is not implemented with a reactive-first design in mind and incurs [serious backpressure issues](/spring-cloud/spring-cloud-gcp/pull/1461#discussion_r274541998) among many other things. I have recently released a new project, [reactor-pubsub](https://github.com/vy/reactor-pubsub), where Reactor is a first-class citizen and the internals are dramatically simpler. We have been using the predecessor of this driver for almost a year at production successfully. I also had the courtesy of @bsideup and @violetagg to review the code. I am confident that `reactor-pubsub` is a better fit as a Pub/Sub driver for the `spring-cloud-gcp` project. Here I kindly ask for feedback to make it so.

**Comment by meltsufin** [comment]
Hi Volkan! How did you get around the issue that `StreamingPull` RPC returns a batch of messages, and you cannot control the size of that batch? This is at the GRPC level. So, it has nothing to do with the client library, or "the driver". That has always seemed like the sticking point for implementing backpressure. So instead, we use the synchronous pull, which allows you to specify the size of the batch, but it's not truly reactive because it doesn't use GRPC streaming.

Are you aware of the [existing Reactive Pub/Sub support](https://cloud.spring.io/spring-cloud-gcp/reference/html/#reactive-stream-subscription) in the project? What do you see as the issues with it compared to reactor-pubsub implementation?

**Comment by vy** [comment]
Thanks for the prompt response @meltsufin!

Yes, I am aware of the existing Reactive Pub/Sub support, but it still uses the official GCP driver which contains the following explosive: `messages.forEach(sink::next)`. Further, it requires a poll period, whereas `reactor-pubsub` supports both long and periodic polling. (Let me know if I am mistaken.)

`reactor-pubsub` has no GCP library dependencies with the exception of authentication. It further uses JSON rather than Protobuf. It doesn't use `StreamingPull`, but basic `pull` (where the batch size is configurable) with long polling. It further ships goodies (metrics, bounded schedulers, etc.) which I personally find vital while running on production.

But these are not the main reason I propose to move away from the GCP driver. My (even though subjective) justification is as follows: GCP driver is over-engineered for such a simple task and lacks the fundamental flow control knobs. I have spent many nights debugging production issues caused by covert thread pools, so-called smart retry and throttling mechanisms, etc. In a nutshell, all a developer needs is `Flux<List<Message>> poll()`, `Mono<Void> ack(List<Message>)`, and `Mono<Void> publish(List<Message>)` methods. The rest of the *smart mechanisms* are one-liners thanks to Reactor.

**Comment by vy** [comment]
Hey @meltsufin! Would you mind sharing some thoughts on how to proceed with this issue, please?

**Comment by meltsufin** [comment]
We're committed to fixing problems with the current implementation which is based on the official Pub/Sub client library (gRPC-based). We welcome reports of specific bugs and performance issues with the current implementation.

Frankly, I still don't see a compelling reason to switch the project to something like the JSON-based Pub/Sub API. GRPC should be faster in principle. Do you have any metrics to demonstrate the performance advantage of your library? Thanks!

**Comment by vy** [comment]
> Do you have any metrics to demonstrate the performance advantage of your library?

- `pubsub-reactor` doesn't suffer from [the back-pressure issues of the official client ](#1461#discussion_r274541998)
- `pubsub-reactor` [can pull+ack ~8GB in ~4sec on a single core](/vy/reactor-pubsub#how-fast-is-reactor-pubsub)

Do you have any certain "metrics" in mind that I need to provide?

**Comment by meltsufin** [comment]
> Do you have any certain "metrics" in mind that I need to provide?

If you are making a claim that `pubsub-reactor` has better performance, then what we want to see would be a direct comparison with [our implementation](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.1.RELEASE/reference/html/#reactive-stream-subscription). Otherwise, I'm not sure how to interpret these numbers.

If the advantages are more about the ease of use around JSON vs. protobuf, then it's a different story. It's great for Pub/Sub customers to have alternative reactive implementations for Pub/Sub. It seems like you did some great work on this one.

**Comment by meltsufin** [comment]
Thank you for your proposal. We decided not to proceed with it for the time being.
