### ISSUE TITLE
Spring Sleuth / GCP PubSub integration

### ISSUE THREAD

**Issue by mauraborean** [spring-cloud/spring-cloud-gcp#2073]
**Is your feature request related to a problem? Please describe.**
I'm using Spring Sleuth in a Spring Boot project and I'd like to include received PubSub events in my metrics. I've read that is it possible to trace RabbitMQ, Kaftka, JMS messages, but I'm having some trouble finding some integration for PubSub.

**Describe the solution you'd like**
I'd like to have some guidance on how to trace this events =) or know if there's an integration possible or in the way.

**Describe alternatives you've considered**
I tried to intercept the method that is executed when the events are received using AspectJ, but it was not possible (at least for me)
Also, I asked for this in https://github.com/spring-cloud/spring-cloud-sleuth/issues/1500

**Comment by meltsufin** [comment]
@mauraborean Can you link to the documentation that references this for other providers like Kafka and RabbitMQ? Can you describe a bit more about how you're using Pub/Sub? Are you using Spring Integration channel adapters or the `PubSubTemplate`?
Tracing context should already be carried through with messages sent via Spring Integration.

**Comment by mauraborean** [comment]
Can you link to the documentation that references this for other providers like Kafka and RabbitMQ? 
Here are the links:
https://cloud.spring.io/spring-cloud-sleuth/reference/html/#spring-rabbitmq
https://cloud.spring.io/spring-cloud-sleuth/reference/html/#spring-kafka

Can you describe a bit more about how you're using Pub/Sub? Are you using Spring Integration channel adapters or the PubSubTemplate?
I am using `PubSubTemplate` (`PubSubSubscriberTemplate` to be more specific)

**Comment by meltsufin** [comment]
@mauraborean Thanks for providing the references.
We definitely do not automatically instrument `PubSubTemplate` to propagate the traces.
This support would probably need to go into the `zipkin-gcp` project, where we handle HTTP trace header propagation.
@artembilan @adriancole WDYT?

**Comment by artembilan** [comment]
May be that should go here: https://github.com/openzipkin/brave/tree/master/instrumentation?
I have had a brief with Marcin, and he suggests to go similar instrumentation configuration model here in this project since Spring Cloud Sleuth can't have a cyclic dependency to this one.
The Brave project may provide low-level API for instrumenting a `Publisher`, which could be used in our project for injecting into the `PublisherFactory`.

**Comment by meltsufin** [comment]
@artembilan I'm not sure I fully understand your suggestion. This project also depends on Brave. So, wouldn't there be a cyclic dependency as well if Brave becomes dependent on Spring Cloud GCP? Is it not a problem because the `spring-cloud-gcp-pubsub` module specifically doesn't depend on Brave?
Previously we put trace propagation logic into this project:
https://github.com/openzipkin/zipkin-gcp/tree/master/propagation-stackdriver

Would it make sense to keep it there? How is this done for Spring Cloud AWS?

**Comment by artembilan** [comment]
Well I didn't say that Brave should depend on SC-GCP. I just said that they need to instrument a `Publisher`, therefore `google-cloud-pubsub` - nothing about Spring.

The AWS is done in the SC-Sleuth since there is nothing like Stackdrive over there in the SC-AWS. Although I see there is AWS X-Ray: https://aws.amazon.com/xray/, which just has to be supported in the SC-AWS. So, the story may change in the future about its support in SC-Sleuth.

If end result is going to be compatible, maybe it is just enough to generate Stackdrive traces from our side. Therefore indeed we could instrument our `PubSubTemplate` by ourselves and only here in this project.

So, I'm mostly speculating - really ignorance with all of this tracing stuff 😄

**Comment by meltsufin** [comment]
Basically, this is going to require some analysis. We'll accept it as a feature request, but no one is scheduled to work on it yet.

**Comment by saturnism** [comment]
Following up on this - the trace id is not carried through to the Spring Integration processor/thread properly.

E.g., A sends B w/ trace ID `123`, and B uses Spring Integration and Pub/Sub, B receives the message but the trace context has trace ID `somethingelse`.

**Comment by saturnism** [comment]
Before processing the message, we may need to setup the current span first, e.g., https://github.com/openzipkin/brave/blob/master/brave/README.md#working-with-callbacks-that-occur-on-different-threads

**Comment by meltsufin** [comment]
Superseded by an issue in zipkin-gcp: https://github.com/openzipkin/zipkin-gcp/issues/190
