### ISSUE TITLE
Question: when to use `Autowired`?

### ISSUE THREAD

**Issue by anguillanneuf** [spring-cloud/spring-cloud-gcp#2123]
Why is there not a need to annotate this messaging gateway with `@Autowired` as described in this [Codelab](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html?index=..%2F..index#4)? @ChengyuanZhao 

https://github.com/spring-cloud/spring-cloud-gcp/blob/a706b9bc9937652e824c70cdd3a6a865b43cbf46/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-sender/src/main/java/com/example/WebController.java#L33

**Comment by elefeint** [comment]
This code is using [constructor injection](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-constructor-injection) instead of autowiring the field directly as the codelab does.
Any classes annotated with `@Controller`, `@RestController` or `@SpringBootApplication` act as configuration classes -- they can declare and consume Spring beans. With [Java-based configuration](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#beans-java), `@Autowired` is generally not necessary/discouraged in real code, but is convenient in tests and sample apps.

**Comment by anguillanneuf** [comment]
Thank you @elefeint for the great explanation!
