### ISSUE TITLE
The method SimpleSpannerRepository#existsById fetches all fields and interleaved child objects

### ISSUE THREAD

**Issue by s13o** [spring-cloud/spring-cloud-gcp#2127]
The method SimpleSpannerRepository#existsById could be implemented by a simple query like `SELECT EXISTS (SELECT 1 FROM %s WHERE %s)` instead of fetching of too many fields and interleaved objects from the database.

**Comment by dmitry-s** [comment]
@s13o I'm working on this issue

**Comment by s13o** [comment]
I'm too. I did as You recommend
pls take a look on https://github.com/spring-cloud/spring-cloud-gcp/pull/2135

**Comment by dmitry-s** [comment]
@s13o I decided to take a different approach. I'm using a read call, as it was done originally; but instead of retrieving all the fields, I only fetch one.
I understand that you put a lot of work in #2135, but I thought you were not going to work on that PR when you closed it.

Going forward we will coordinate our efforts!

**Comment by s13o** [comment]
well, I did a force-push for a batter commit history and it closed the PR
Basically I'd planned to resolve the #2127 and then #2132 because I thought they depend on each other in a part of the building of sql-where for KeySet.
So, will see after the merge - probably I'll be able to suggest some improvements
