### ISSUE TITLE
Dependencies bom manages dependencies that do not exist

### ISSUE THREAD

**Issue by wilkinsona** [spring-cloud/spring-cloud-gcp#2138]
The dependencies bom contains dependency management for `spring-cloud-gcp-trace` but the module no longer exists.

**Comment by wilkinsona** [comment]
`spring-cloud-gcp-config` has the same problem.

**Comment by meltsufin** [comment]
You're absolutely right about the `spring-cloud-gcp-trace` one because it's a module we removed at some point. However, `spring-cloud-gcp-config` and `spring-cloud-gcp-starter-config` are modules that we do not promote to Maven Central because we consider them as "beta", but we do want them to be published to snapshots and milestones.
I guess we just have to use the `central` profile for that.

**Comment by meltsufin** [comment]
Actually, I'm not sure how we could use a Maven profile for this. I guess, we'll just have to tell the users of `spring-cloud-gcp-starter-config` to specify the version.
Oh, and `spring-cloud-gcp-config` doesn't exist.
