### ISSUE TITLE
Disabling auto-configuration of instrumenting executor beans reduces visibility

### ISSUE THREAD

**Issue by JBodkin-LH** [spring-cloud/spring-cloud-gcp#2148]
**Describe the bug**
The documentation for 1.2.1 recommends to disable `spring.sleuth.scheduled.enabled=false` to prevent many traces appearing with the name `async`. This is problematic for applications that use executors under the hood, which can be commonly used in reactive programming when running IO requests or running asynchronous code.

The workaround to exclude the thread pool bean created by this project would be a better recommendation rather than disabling the setting. Ideally as mentioned in the original issue, it would be best to automatically exclude the code in this project from being traced.

Reference: https://github.com/spring-cloud/spring-cloud-gcp/issues/1978

**Sample**

**Comment by elefeint** [comment]
I opened #2016 a couple of months back to completely hide the internal scheduler pool from the spring context.
This might be a good first issue, actually, since #2013 provides an example of hiding a scheduler in another one of our autoconfigurations.

Would you be interested in contributing the code?
