### ISSUE TITLE
How to write custom query with Spring FirestoreReactiveRepository

### ISSUE THREAD

**Issue by p595285902** [spring-cloud/spring-cloud-gcp#2235]
Just wanted to make sure the question opened in [stackoverflow ](https://stackoverflow.com/questions/60518350/how-to-write-custom-query-with-spring-firestorereactiverepository) will get your attention.

**Comment by dzou** [comment]
Hey @p595285902 - will take a look at this for you shortly...

**Comment by dmitry-s** [comment]
@p595285902 we don't support `@Query` custom queries because there is no query language in Cloud Firestore. I could recommend using name based query methods:
```
public interface UserRepository extends FirestoreReactiveRepository<User> {
    Flux<User> findByAge(Integer age);

    Flux<User> findByAgeGreaterThanAndAgeLessThan(Integer age1, Integer age2);

    Flux<User> findByAgeGreaterThan(Integer age);

    Flux<User> findByAgeGreaterThan(Integer age, Pageable pageable);

    Mono<Long> countByAgeIsGreaterThan(Integer age);
}
```
See [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.RC1/reference/html/#spring-data-reactive-repositories-for-cloud-firestore) for more details.

**Comment by p595285902** [comment]
Thanks for the quick reply.
> Cloud Firestore **only** supports filter components joined by **AND**, and the following operations:

Is OR going to come anytime soon?

**Comment by p595285902** [comment]
Thank you.
