### ISSUE TITLE
The maxMessage argument in the PubSubTemplate pull method must be a positive number

### ISSUE THREAD

**Issue by mzeijen** [spring-cloud/spring-cloud-gcp#2248]
The PubSubTemplate pull methods have a nullable maxMessage argument, which allows `null`. However, according to the Google PubSub API docs the pull request maxMessage must always have a positive number (see: https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#pullrequest). 
Currently if null is provided via PubSubTemplate then 0 is send to PubSub, which is wrong.

**Comment by dzou** [comment]
I can fix this.

**Comment by dzou** [comment]
@meltsufin, @elefeint - do you guys recall why we used an object Integer type instead of primitive for the maxMessages param [in the interface](https://github.com/spring-cloud/spring-cloud-gcp/blob/2adf4328c819a634a3ad7a1627426badf198c4fb/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/subscriber/PubSubSubscriberTemplate.java#L265)?

**Comment by elefeint** [comment]
Dates back to #283; unlikely to be intentional.
My first reaction was that we can't change it now because old working code would now NPE on unboxing, but a `null` parameter will lead to an unset required proto field, causing a cryptic error, so it's not a regression so much as exchanging a misleading exception for a meaningful one.

**Comment by dzou** [comment]
I see. If null means "absent" could it be reasonable to set the maxMessages field to MAX_INT then if the field is provided? I.e. if there is no maximum, then any number of messages is allowed.

**Comment by elefeint** [comment]
That's an interesting idea! Nothing we do right now contradicts it. 
@meltsufin ?

**Comment by meltsufin** [comment]
It's nullable because it's an optional parameter to PullRequest.
In `DefaultSubscriberFactory.createPullRequest` we have this logic.
```java
		if (maxMessages != null) {
			pullRequestBuilder.setMaxMessages(maxMessages);
		}
```

So, I actually don't see any issue with it being nullable.

**Comment by elefeint** [comment]
`maxMessages` is a required field in `PullRequest`, so the service call will fail if it's not set.

Sources: [docs](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#pullrequest) and bitter experience.

**Comment by dzou** [comment]
Yup, the `maxMessages` is a required field in the proto.

**Comment by meltsufin** [comment]
In that case, the MAX_INT idea makes sense. Let's make sure we document it though. Thanks!
