### ISSUE TITLE
Add option to explicitly request separate session context for new Spanner requests

### ISSUE THREAD

**Issue by NickChapman** [spring-cloud/spring-cloud-gcp#2291]
**Is your feature request related to a problem? Please describe.**
I am trying to send parallel requests to Spanner, but even though my requests queue up asynchronously, they are executed sequentially. I believe (and I could be wrong here) that this is because they are being executed using the same session.

**Describe the solution you'd like**
In `SpannerTemplate`, add an option to explicitly request that a transaction be executed in a new (or just different) session than the one that is currently being used.

**Describe alternatives you've considered**
I'm not sure if there are any alternatives, please let me know if there are!

**Additional context**

**Comment by meltsufin** [comment]
We don't manage Spanner sessions directly. The Spanner Client Library does. We simply configure the session pool for it. You can try playing with the `spring.cloud.gcp.spanner.minSessions` and `spring.cloud.gcp.spanner.maxSessions` as [documented](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#cloud-spanner-settings). I'm surprised you're seeing requests all execute in the same session though because even with the default values, the session pool has more than one session.

Maybe an app that reproduces the issue would help in debugging this.

**Comment by meltsufin** [comment]
Re-open if you have further questions.
