### ISSUE TITLE
Support for Spanner Emulator

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-gcp#2298]
cloud sdk version 287.0.0 has release a beta spanner emulator. I am wondering if the project can start with the support for it.

**Comment by elefeint** [comment]
Related: we have a Pub/Sub emulator rule that only lives in Spring Cloud Streams tests. I wonder if we should create a `spring-cloud-gcp-test-support` project to put those emulator rules in.

**Comment by eddumelendez** [comment]
> I wonder if we should create a spring-cloud-gcp-test-support project to put those emulator rules in.

I like the idea.

Also, this tasks will help to find a place for #2281

**Comment by eddumelendez** [comment]
@elefeint thinking about having `spring-cloud-gcp-test-support` and moving the emulators auto-configuration doesn't seems right due to can be also apply for local development. `spring-boot` provides database, ldap and mongo for local development but in the `test-support` we can provide another kind of stuff like annotations which help and improve the emulators autoconfiguration for test specifically.

**Comment by elefeint** [comment]
Right, there are two separate things. One is making emulator work for general case (@dmitry-s is looking into that; it might Just Work because we don't instantiate a transport channel ourselves, relying instead on the client library's default behavior).
The other one is easing use of emulator in integration tests; that's what the test support could help with.

**Comment by dmitry-s** [comment]
Closed in favor of #2318
