### ISSUE TITLE
Running emulator with LocalDatastoreHelper

### ISSUE THREAD

**Issue by thameenas** [spring-cloud/spring-cloud-gcp#2329]
I was trying to run my integration tests using LocalDatastoreHelper.But this is either using my service account credentials or the default credentials. Is there any way to run tests using LocalDatastoreHelper without the credentials?
I wanted to run these integration tests on pipeline too, but the credentials are causing it to fail.

**Comment by dmitry-s** [comment]
I'm looking into it.

**Comment by dmitry-s** [comment]
It is actually already implemented. See [GcpDatastoreAutoConfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/datastore/GcpDatastoreAutoConfiguration.java#L103).

In short, if you  have `spring.cloud.gcp.datastore.host` or `spring.cloud.gcp.datastore.emulator.enabled` properties set, the autoconfiguration will use `NoCredentials`. See our docs for more details: 
1) [properties](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#cloud-datastore-settings) 
2) [emulator autoconfiguration](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.2.RELEASE/reference/html/#datastore-emulator-autoconfiguration)

Feel free to reopen this issue if that doesn't work.

**Comment by thameenas** [comment]
Thanks, it worked. But why does localDatastoreHelper class say "This class is unstable"? 
Also, Ive been noticing that the integration test sometimes fails, but re running the test would make it pass. Is there any reason for this flaky behaviour?

**Comment by dmitry-s** [comment]
Hi @thameenas 

I guess it's unstable because it can change in the future.

As for flakiness, the reason is most likely in the latency. After you write something to the Cloud Datastore, sometimes it would take a couple of seconds to propagate this change to all backends. This is happening because global queries in Datastore are [eventually consistent](https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency) and not strongly consistent  .

I would recommend using [awaitility](https://github.com/awaitility/awaitility) to keep retrying for a specified time limit.

Let us know if you have more questions.
