### ISSUE TITLE
Support for reactive publish to Pub/Sub?

### ISSUE THREAD

**Issue by rubasace** [spring-cloud/spring-cloud-gcp#2425]
It seems like `PubSubReactiveFactory` only supports polling but not publishing. 

I'm not sure about this one, but I'm worried using the normal `PubSubTemplate` might have negative consequences to applications performance as they don't use `Schedulers` but `Executors` instead, potentially leading to more threads than desired running in the applications. Please correct me if I'm wrong, I'm not an expert on the matter.

Anyway, could someone clarify me if this is a potential problem and there are plans to support a reactive publishing or, otherwise, if `PubSubTemplate` is safe to use on a reactive stack?

**Comment by elefeint** [comment]
Cross-posting answer from the [StackOverflow thread](https://stackoverflow.com/questions/62388716/reactive-support-for-publishing-to-google-pubsub-topic/62441102).

`PubSubTemplate` publish methods are asynchronous, and so are safe to use in a reactive app in the sense of "safe" that they won't lock up your limited pool of processor-bound threads.

Having fewer thread pools is a good goal in itself because it lets Project Reactor more efficiently allocate work. The publisher thread pool is useful, though -- it manages async sending of messages in batches. It uses 4 threads by default, which you can customize with `spring.cloud.gcp.pubsub.publisher.executor-threads`. 

We've originally created `PubSubReactiveFactory` to provide idiomatic reactive stream support with backpressure, as the streaming pull, while efficient, did not allow for message-level backpressure. It would not bring a lot of value to implement reactive publishing, as it would use the same `PubSubTemplate` publish methods, get a `CompletableFuture` out of the Spring `ListenableFuture` and turn that into a `Mono` of the `String` message ID.

**Comment by rubasace** [comment]
Replied on my colleague's post on SO. Closing this issue here.
