### ISSUE TITLE
Getting 'StructuredQuery.from cannot have more than one collection selector' from reactive repositories

### ISSUE THREAD

**Issue by adirepo** [spring-cloud/spring-cloud-gcp#2510]
Spring boot parent version  - 2.3.2.RELEASE
Spring cloud version - Hoxton.SR6

When running load test on my application getting below exception quite frequently.

`org.springframework.cloud.gcp.data.firestore.util.ObservableReactiveUtil$StreamingObserver.onError(ObservableReactiveUtil.java:126) at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:453) at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source) Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: StructuredQuery.from cannot have more than one collection selector. at io.grpc.Status.asRuntimeException(Status.java:533)`

**INVALID_ARGUMENT: StructuredQuery.from cannot have more than one collection selector. at io.grpc.Status.asRuntimeException(Status.java:533)**

I am not querying on multiple collections in a single query, in-fact I am extending FirestoreReactiveRepository in it's plain form for my collections and writing methods in it for query (just like JPA). I am getting these errors for 3 repositories in my 2 Spring boot services, so I assume it won't be problem with just one of my collection. This happens when there is huge load on service, running small bunch of requests work fine.

**Comment by meltsufin** [comment]
@dmitry-s PTAL.

**Comment by manishjain5238** [comment]
@meltsufin @dmitry-s Any updates on this issue. As I am also getting same issue, although I am accessing single collection only?
When I attempt to access firestore, I first get error "{io.grpc.StatusRuntimeException: UNAVAILABLE: io exception}" and later when I retry same code then get error "{io.grpc.StatusRuntimeException: INVALID_ARGUMENT: StructuredQuery.from cannot have more than one collection selector.}"

**Comment by manishjain5238** [comment]
Also this issue is not consistent, same code works fine for all cases but sometimes gives this in consistent behavior.
I am also using FirestoreReactiveRepository

**Comment by dmitry-s** [comment]
@manishjain5238 Could you provide the source code so we can try to replicate the issue?

**Comment by mhbarney** [comment]
@dmitry-s , I experienced this issue and managed to resolve it, but I'm not sure exactly why my solution worked. Here's some code roughly the same to what was causing my problem:

```java
  private Mono<SeasonMetadata> getSeasonMetadata(Timestamp timestamp) {
    Flux<SeasonMetadata> seasonMetadata =
        seasonMetadataRepository.findByEndGreaterThan(timestamp);
    Mono<SeasonMetadata> seasonMetadata =
        seasonMetadata
            .filter(metadata -> metadata.getStart().compareTo(timestamp) <= 0)
            .next();  // <- annotation 1 
    return seasonMetadata;
  }

  public Flux<SeasonStats> updateResults() {
    Mono<SeasonMetadata> currentSeasonMetadata = getSeasonMetadata(Timestamp.now());
    Flux<Player> players = playerRepository.findAll();

    return players.flatMap(  // <- annotation 2
        player ->
            currentSeasonMetadata.flatMap(
                metadata -> {
                  Stats parent = new Stats();
                  parent.setId(metadata.getId());
                  SeasonStats playerStats = new SeasonStats();
                  playerStats.setPlayerId(player.getId());
                  return firestoreTemplate.withParent(parent).save(playerStats);
                }));
  };
```


The call to `FirestoreTemplate::save`  in `updateResults()` was not successful. When I changed the call of `next()` instead to `publishNext()` at the line marked **annotation 1**, then the problem went away. I realized also that I should invert the nested `flatMap` calls at **annotation 2** to look like:

```java
currentSeasonMetadata.flatMapMany(
        metadata ->
            players.flatMap(
                player -> {
```
^ And in that case, either `next()` or `publishNext()` worked fine.

However, since I'm somewhat new to Reactor, I'm not sure how this could cause the query to be built incorrectly. Any updates would be appreciated. Thanks!

**Comment by dmitry-s** [comment]
@mhbarney I tried replicating the issue using your code, but it works fine for me. 
Would you be able to provide an application that reproduces the error?

Thanks!

**Comment by dmitry-s** [comment]
@mhbarney I finally was able to reproduce it. I'll let you know when we have updates.

**Comment by dmitry-s** [comment]
@mhbarney the issue is caused by double subscribing to the `currentSeasonMetadata`. It happens because you have `currentSeasonMetadata.flatMap` inside of `players.flatMap`. That `Mono` doesn't currently support double subscription, and I will create a fix for allowing that.

But in this case I think you don't actually want to fetch new `currentSeasonMetadata` for every player, so my suggestion would be to call `chache()` method on that `Mono`, like so:
```
    Mono<SeasonMetadata> currentSeasonMetadata = getSeasonMetadata(Timestamp.now()).cache();

```

And that should fix your issue.

Let me know if that works for you.

Thanks!

**Comment by mhbarney** [comment]
@dmitry-s thank you, using `cache()` also worked. I'll also take a look at the code changes you made to learn more.
