### ISSUE TITLE
java.lang.ClassCastException while implementing writeGcs() as given example  in https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-examples/spring-cloud-gcp-storage-resource-example/src/main/java/com/example/WebController.java

### ISSUE THREAD

**Issue by pankajnd20** [spring-cloud/spring-cloud-gcp#254]
**error description** :
java.lang.ClassCastException: org.springframework.web.context.support.ServletContextResource cannot be cast to org.springframework.core.io.WritableResource

**error line**  :
try (OutputStream os = ((WritableResource) this.gcsFile).getOutputStream())

**full code** :

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.WritableResource;

 @Value("gs://mybucketname/my-file.txt")
    private Resource gcsFile;

public String readGcsFile() throws IOException {
        return StreamUtils.copyToString(
                this.gcsFile.getInputStream(),
                Charset.defaultCharset()) + "\n";
    }

    String writeGcs(String data) throws IOException {
        try (OutputStream os = ((WritableResource) this.gcsFile).getOutputStream()) {
            os.write(data.getBytes());
        }
        return "file was updated\n";
    }

why it's casting super class to sub class in the example ?

**Comment by meltsufin** [comment]
It looks like you're missing the Google Cloud Storage Spring Boot Starter dependency and the `gs://mybucketname/my-file.txt` URI is being interpreted as a  `ServletContextResource` rather than the `GoogleStorageResource`. Hence, you're unable to cast to `WritableResource`, which is not implemented by `ServletContextResource`.

Does your `pom.xml` contain this dependency?
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-storage</artifactId>
</dependency>
```

The reason we have to cast is because `@value` currently only works with the `Resource` types, not `WritableResource`. See this issue on the JIRA tracker: https://jira.spring.io/browse/SPR-10656.

**Comment by pankajnd20** [comment]
Already added the mentioned dependency in pom.xml.  Also checked library exist in project or not .
Though getting this error.

**Comment by meltsufin** [comment]
Can you share a complete example that reproduces this? Maybe change our [example](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-examples/spring-cloud-gcp-storage-resource-example) to match your setup.

**Comment by saturnism** [comment]
@pankajnd20 could i trouble you to check my example here?
https://github.com/saturnism/spring-cloud-gcp-guestbook/tree/master/6-storage/guestbook-frontend

Also, some lab instructions I used:
https://docs.google.com/document/d/14NRxngEhkh1gPTyTS-V51XEHrGMhJKnbzw5uSs6oFaI/edit#heading=h.4civimycga8m

Cheers,

**Comment by joaoandremartins** [comment]
Also, in your example you don't seem to be writing to the resource.

**Comment by joaoandremartins** [comment]
Please reopen if are still seeing this issue.

**Comment by saurabhguptasg** [comment]
Hi all, this issue is still occurring
with the storage and starter dependencies both included, the resource gets created as a ServletContext resource and throws a cast exception for `WritableResource` when invoking:
`OutputStream storageOutputStream = ((WritableResource)storageObject).getOutputStream();`
the sample referenced in this bug has now moved to:
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/src/main/java/com/example/WebController.java

**Comment by sayi65** [comment]
i get the same issue.
I wrote the same source as the example

error:
org.springframework.web.context.support.ServletContextResource cannot be cast to org.springframework.core.io.WritableResource

**Comment by joaoandremartins** [comment]
There is a working Storage code sample in https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample.

Would you mind trying it and then adapting to reproduce the issue you're seeing? Please let us know when you were able to do so.

**Comment by sayi65** [comment]
@joaoandremartins
OK thank you for your comment
