### ISSUE TITLE
Consider renaming spring-integration-gcp

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#269]
`spring-integration-gcp` is a bit weird. I understand why it was named that way but all modules should ideally start with the same prefix. 

Regardless and unless this is meant to be contributed back to Spring Integration, the package should not start with `org.springframework.integration`.

**Comment by meltsufin** [comment]
@garyrussell @markfisher I believe one of you suggested this module naming.

**Comment by artembilan** [comment]
Right, my original thought was do not rely on the Spring Integration packaging. Since this is a part of `spring-cloud-gcp` so the `group` must indeed be the same and the module should have a name like `spring-cloud-gcp-integration`.

Or, we should extract that part to the separate project and already there name it after original Spring Integration.

Other thoughts are welcome!

**Comment by markfisher** [comment]
I think partly this was modeled after https://github.com/spring-projects/spring-integration-aws

However in hindsight the same suggestion should have been made for that project.

I agree with the names suggested by Artem if this remains within `spring-cloud-gcp` (and I think it should since it's the middle of a sandwich between the PubSub support and the Spring Cloud Stream Binder implementation).

**Comment by garyrussell** [comment]
I would prefer to keep the artifact with this name.

If it's not appropriate in this repo, we could move it to the [spring-integration-extensions](https://github.com/spring-projects/spring-integration-extensions) repo or create a separate top-level repo in spring-projects like https://github.com/spring-projects/spring-integration-aws

**Comment by garyrussell** [comment]
>and I think it should since it's the middle of a sandwich between the PubSub support and the Spring Cloud Stream Binder implementation

I am ok with that too 😄

**Comment by meltsufin** [comment]
Is my reading correct that most of you are leaning towards the rename? :smile:
