### ISSUE TITLE
Add starter module to inject GoogleCredentials into application context

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#3]
The basis for any interaction with google libs is it's credentials object being available. There are a handful of ways to bootstrap it. 
This module should provide a boot starter that will bootstrap a bean of type `Credential` and will use Conditinal logic to determine what type of `Credential` it will create

**Comment by joaoandremartins** [comment]
I realise that `CredentialsAutoConfiguration` is already in its own started and provides pretty good functionality. It tries to get the credentials from the environment/properties and, if none are there, it uses the application's default credentials.
It seems like all use cases are covered?

My only peeve is that, due to the ResourceLoader internals, we're having to specify the location as in

`cloud.gcp.auth.location=file:/usr/local/...`

Is there another way to do this with the ResourceLoader that doesn't require providing a URL and that doesn't get the path as a relative one?
If this is a manifest expectation for usage of the tool, then I'm fine with it.

**Comment by viniciusccarvalho** [comment]
What do you mean? The gcloud auth from my understand only works if you provide the file or the auth default. There's a separate issue with the CloudFoundry broker that we don't want to address in this repo.

And it's not only the resource loader, any class that uses the starter, and wants a bean of GoogleCredentials to be created will need to decide either to use default or provide the location of the file.

**Comment by joaoandremartins** [comment]
I want to be able to say `/usr/local/...` and not `file:/usr/local/...`, but not fussed if no can do, as long as we have some documentation on what users must specify. I had to do a little bit of digging to find out that the path was considered to be relative, not absolute.

So GoogleCredentialsAutoConfiguraiton already probes env var "cloud.gcp.auth.location" (I think this covers both that property AND System.getProperty()?) and falls back to the credentials default. Any more requirements here that prevent us from marking this as resolved?

**Comment by viniciusccarvalho** [comment]
The file abstraction is a Spring feature, it's documented here: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html, and it's actually we can make it possible the `gs://` abstraction, we need to know the protocol. I don't think that a `/` would defer to file, it would probably look in the classpath.

The property can be `System.getProperty`, that's part of boot's relaxed binding. I'll submit an enhancement to it to use the GcpProperties instead of just a hardcoded string. But in the end, it will look in the same place for the value.

**Comment by joaoandremartins** [comment]
Sweet! Then it sounds like we can close this issue?
I'm also interested in what we can do for non-Boot users regarding credentials.
