### ISSUE TITLE
spring-cloud-gcp-starter-sql brings too many dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#321]
`spring-cloud-gcp-starter-sql` brings driver-related dependencies for both MySQL and PostgreSQL. It is up to the user to choose this and someone using Postgresql shouldn't have the mysql driver on the classpath.

If you remove those, then the starter doesn't bring anything which is a nice illustration of the work that has been done in #262

**Comment by joaoandremartins** [comment]
One way to resolve this is to create two starters instead, `spring-cloud-gcp-starter-sql-mysql` and `spring-cloud-gcp-starter-sql-postgresql`. WDYT?

But taking a step back, why is having a bigger classpath is an issue now, but wasn't for `autoconfigure`? FTR I'm in for having only what we need in the classpath, would just like to better understand our motivations.

The way it works now is that we set the necessary dependencies for users, so that they won't even need to know them. Then, they can just set `spring.cloud.gcp.sql.database-type=mysql` or `postgresql`, and we provide the correct beans that way.

With or without separate starters, I do think there's value in having starters for SQL so that the dependencies are sorted out and the user doesn't need to worry about them (e.g., not know about `com.google.cloud.sql.mysql-socket-factory`, etc.)

**Comment by meltsufin** [comment]
We may actually be able to get rid of the `spring.cloud.gcp.sql.database-type`, if we separate MySQL dependencies from the PostgreSQL ones. I like that.

If the Spring Boot Initializr has support for this, we may not really need separate starters for MySQL and PostgreSQL. Although I do agree that having `spring-cloud-gcp-starter-sql-mysql` and `spring-cloud-gcp-starter-sql-postgresql` won't hurt, if we accept that pass-through starters are OK.

**Comment by meltsufin** [comment]
Note that https://github.com/spring-cloud/spring-cloud-gcp/pull/319 is attempting to address this issue.

**Comment by snicoll** [comment]
Again, autoconfigure does not (should not) have a "big classpath". Dependencies are marked optional so they won't transmit to user's projects. 

I don't think a starter for MySQL and PostgreSQL is a good idea. The user should decide which database they want to use and GCP shouldn't express that choice as a first class concept.

**Comment by joaoandremartins** [comment]
Why shouldn't GCP express that choice as a first class concept?
The Cloud SQL product certainly does so, and the difference between having it in a property vs through a dependency is basically the null.
My preference falls strongly for having two separate starters since we can manage the dependencies for users, therefore making their lives easier. It's part of the value I originally envisioned for our starter -- setting a "MySQL/PostgreSQL" property is way simpler than having to include two separate dependencies.

Yes, the JAR is really mandatory. It's what creates the connection to the instance, using the specified credentials, etc.

**Comment by snicoll** [comment]
> Why shouldn't GCP express that choice as a first class concept?

Because declining a starter for each database version you support doesn't feel right. If you add support for two additional databases, are you going to create two more starters? The driver is out of your hand so it's a matter for the user to add the special jar. The auto-configuration  should detect if it is present and back-off otherwise. That seems sane to me.

**Comment by joaoandremartins** [comment]
> The driver is out of your hand

I think this is the main misunderstanding here. It's the exact opposite. It is an explicit goal of our starters to determine which driver will be used. That's how we don't even ask users for any JDBC driver class name and we keep configuration very simple, just like in the Spring way.
Otherwise, we'd just be using the generic `spring-boot-starter-data-jpa`.

**Comment by snicoll** [comment]
> It's the exact opposite. It is an explicit goal of our starters to determine which driver will be used

I think that's wrong. You should't bring mysql and postgresql driver by default. As a matter of a fact you shouldn't bring any driver at all. With that chain of thoughts, the starter only brings the matching google-specifc jar for the database the user has chosen and that's not something that requires a starter.

To bring a start.spring.io use case, you select postgresql or mysql (the existing entries) because you're expression an opinion on the database that you want to use. The starter shouldn't overrule that.

**Comment by joaoandremartins** [comment]
Since Spring Boot already mandates a version for `mysql.mysql-connector-java` and `org.postgresql.postgresql`, I think it might still be possible to let the user specify the dependency while filling in the driver name on the user's behalf, so they don't have to.

If that's possible, then sure, let's remove the dependencies. If not, then I feel very strongly for continuing to specify the JDBC driver class name for the user.

**Comment by snicoll** [comment]
> I think it might still be possible to let the user specify the dependency while filling in the driver name on the user's behalf, so they don't have to.

Sorry I lost you. Spring Boot already auto-configures the driver based on the JDBC url if that's what you're asking but if you do, I don't  understand the link between that and this issue.

**Comment by joaoandremartins** [comment]
Closed by #364
