### ISSUE TITLE
Cloud SQL sample is broken

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#337]
Running the SQL code sample results in the following error:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webController' defined in file [/usr/local/google/home/joaomartins/workspaces/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-sql-sample/target/classes/com/example/WebController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.jdbc.core.JdbcTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:729)
```
If all references to `JdbcTemplate` are removed from the code, the auto configuration kicks in. However, when the user code autowires a `JdbcTemplate` object, Spring Boot tries to instantiate it before `GcpCloudSqlAutoConfiguration` runs. Since at that time, there is no `DataSourceProperties` bean in the context, there also isn't any `DataSource` and therefore, no `JdbcTemplate`.

**Comment by ChengyuanZhao** [comment]
I think the `GcpCloudSqlAutoConfiguration` class is loaded and "run"/gets its beans registered in time.

For example, if you add this bit: 
```	@Bean
	public JdbcTemplate jdbcTemplate() {
		return new JdbcTemplate();
	}
```
To that class, then you see different error about jdbc template not being created properly (instead of the error about there being no bean for it), so I think that implies this auto  config class is being read and its beans registered. Perhaps there's just a missing bean definition along the chain somewhere?

**Comment by ChengyuanZhao** [comment]
@joaoandremartins @meltsufin I'm not familiar the cloud sql module here. Is there supposed to be a bean that makes a `DataSource` from `DataSourceProperties` or something? The issue seems to just be not enough beans defined, but the auto config class does seem to be working.

**Comment by joaoandremartins** [comment]
What I found on my cursory tests was that if I have breakpoints anywhere in the `GcpCloudSqlAutoConfiguration` class and I autowire a `JdbcTemplate` object, I get that error and no breakpoints are hit.

On the other hand, if I remove all the `JdbcTemplate` references from my class, the breakpoints are hit and autoconfiguration proceeds normally.

This poses a problem, because autoconfiguration is useless if I can't use it to autowire a `JdbcTemplate` object. :) However, I do not know yet why Spring Boot is trying to instantiate `JdbcTemplate` before `GcpCloudSqlAutoConfiguration`, that's what needs to be investigated.

**Comment by ChengyuanZhao** [comment]
This may be a dumb question, but how are you certain that a JdbcTemplate should even be automatically available as a bean with all dependencies satisfied? 

I tried setting a breakpoint after adding the bit of code I mentioned earlier to `GcpCloudSqlAutoConfiguration`:
```
@Bean
	public JdbcTemplate jdbcTemplate() {
		return new JdbcTemplate();   <--- breakpoint here gets hit.
	}
```
I did not remove modify the sample module at all to remove usage or reference to the JdbcTemplate, and the breakpoint is hit, and the bean definition for JdbcTemplate in GcpCloudSqlAutoConfiguration is used. 

It seems like to me that just there are not enough beans defined to satisfy the requirements to create a JdbcTemplate, and that the GcpCloudSqlAutoConfiguration class is being used as expected.

**Comment by joaoandremartins** [comment]
That happens because you are replacing `spring-jdbc` as the creator of `JdbcTemplate`, by providing that bean, which you shouldn't be.

> It seems like to me that just there are not enough beans defined to satisfy the requirements to create a JdbcTemplate, and that the GcpCloudSqlAutoConfiguration class is being used as expected.

Exactly. As I also mentioned before,

> Since at that time, there is no DataSourceProperties bean in the context, there also isn't any DataSource and therefore, no JdbcTemplate.

**Comment by ChengyuanZhao** [comment]
You're missing the point of my demonstration. 

I know I am creating a useless dummy bean, but the point is that it is being read and it is in the same file as the bean for `DataSourceProperties`, which means DataSourceProperties bean is also working. So that means your theory about it not being in the context is not correct, and that the reason the JdbcTemplate wasn't created was because there never existed the correct definition of beans in the code. I could be wrong, but that's what the evidence implies to me.

**Comment by meltsufin** [comment]
I think the real problem is not whether `GcpCloudSqlAutoConfiguration` is kicking in or not, but that the sample is not working, and it used to work before. So, can we just investigate that issue? Thanks!

**Comment by ChengyuanZhao** [comment]
Looks like it stopped working after PR #306 , I'll look into that.

**Comment by ChengyuanZhao** [comment]
I think the issue is caused by not being able to create a `GcpProperties` bean, which is needed to create a `GcpCloudSqlAutoConfiguration`, which is then used to create the `DataSourceProperties`, which is needed to create the `JdbcTemplate`. 
The not-being-able-to-get a `GcpProperties` bean also started with #306 , so I think it's a cause of the problem.

**Comment by meltsufin** [comment]
Thanks for the investigation! How can this be fixed though?

**Comment by ChengyuanZhao** [comment]
Yea still looking, @meltsufin , i'm not sure why the GcpProperties bean isn't available at the moment.

**Comment by ChengyuanZhao** [comment]
I had something configured wrong, the GcpProperties bean and DataSourceProperties beans do work for me :/
