### ISSUE TITLE
Integration inbound/outbound handlers for Storage

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#34]
Create inbound/outbound gateways for Storage. Inbound should be based on `AbstractRemoteFileStreamingMessageSource`

**Comment by joaoandremartins** [comment]
@artembilan quick question for you.

Does `S3StreamingMessageSource` only support `/BUCKET/FOLDER/OBJECT` paths?

The reason I ask is because all the [S3StreamMessageSource tests](https://github.com/spring-projects/spring-integration-aws/blob/master/src/test/java/org/springframework/integration/aws/inbound/S3StreamingChannelAdapterTests.java#L113) assume a `subdir/a.test` kind of file name.

Also, calling my adapter in the following fashion is calling `Session.readRaw`, and I don't understand why. `readRaw()` fails because it expects a `/BUCKET/OBJECT`path but it's getting the remote directory instead.

```
  @Bean
  @InboundChannelAdapter(channel = "blobChannel", poller = @Poller(fixedDelay = "5"))
  public MessageSource<InputStream> inboundAdapter(Storage gcs) {
    StorageInboundChannelAdapter adapter =
            new StorageInboundChannelAdapter(new RemoteFileTemplate<>(new GCSSessionFactory(gcs)));
    adapter.setRemoteDirectory("springone-houses");
    adapter.setFilter(new AcceptOnceFileListFilter<>());
    return adapter;
  }
```

**Comment by artembilan** [comment]
I'm not sure what's going on in your (invisible)  code, so I don't consider this as a quick question 😉 

Well, no. `S3StreamingMessageSource` doesn't require that style. You can use `/BUCKET/FOLDER/OBJECT`.

More over everything in AWS S3 is like `key <-> value` - `BUCKET` -> `OBJECT`. That is already your application logic to distinguish object in the virtual sub-directories. Well, the same way works even FTP, seems for me...

We do there exactly this `String[] bucketKey = path.split("/", 2);`, so we always have an array like `[/BUCKET, /FOLDER/OBJECT]`. The second element is really a key to the object, independently if its prepended virtual directory.

**Comment by joaoandremartins** [comment]
I uploaded what I have to far to https://github.com/spring-cloud/spring-cloud-gcp/tree/gh-34-si-storage-adapters/spring-integration-gcp/src

If you run this [test](https://github.com/spring-cloud/spring-cloud-gcp/blob/gh-34-si-storage-adapters/spring-integration-gcp/src/test/java/org/springframework/integration/gcp/storage/inbound/StorageInboundChannelAdapterTest.java), you'll see that `readRaw()` is called. I don't really understand why SI is trying to read the remote directory as a blob, there must be something I'm missing.

**Comment by artembilan** [comment]
I don't understand your question. Sorry.
`readRaw()`  indeed must read a target remote file. 
Not sure what is "directory" concept in Google Storage, but you definitely can't (and shouldn't) get `InputStream` from the dir.

More over I see this code in your `GCSSession` - `String[] tokens = path.split("/", 1);`.
Since `limit` is `1` there is definitely nothing to split - the input string (e.g. `gcsbucket/gcsfilename`) is returned as is. When I change it to `path.split("/", 2)` (the same what I've shown your in SI-AWS), I jump into the `Channels.newInputStream(this.gcs.reader(tokens[0], tokens[1]))` correctly. But there already no Mockito stub on the matter and I fail with error. Nevertheless it is alrady different story...

**Comment by joaoandremartins** [comment]
Yep, that seems to have been the problem.
Documentation around `limit` isn't very clear, but I think 2 is what we want.
Sorry to bother, have a great holiday!
