### ISSUE TITLE
SQL autoconfig only kicking in for MySQL SocketFactory

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#345]
`@ConditionalOnClass(com.google.cloud.sql.mysql.SocketFactory.class)`

should be

`@ConditionalOnClass({com.google.cloud.sql.mysql.SocketFactory.class, com.google.cloud.sql.postgres.SocketFactory.class})`

**Comment by balopat** [comment]
@joaoandremartins  I think that it should be two @ConditionalOnClass annotations, one for each, instead of a list of the two classes as the value argument.

In my understanding based on [OnClassCondition](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/OnClassCondition.java#L129) if you have both classes as a list then both of them should be on the classpath to trigger the autoconfig, which is weird. I think we want logical OR, and not AND, right?

**Comment by joaoandremartins** [comment]
@balopat I hadn't thought about that, I think you're right, yes.

**Comment by joaoandremartins** [comment]
*bump* how's it going @balopat ? :)

**Comment by meltsufin** [comment]
I think we should split the Cloud SQL starter into two, and then this wouldn't be an issue.

**Comment by balopat** [comment]
haven't had time to continue yet to see if there is an alternative but it seems that splitting is a clean, viable option if it's not too big of a deal.

**Comment by meltsufin** [comment]
Resolved in #364
