### ISSUE TITLE
Create spring-cloud-gcp-starter

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#351]
As per the suggestion in https://github.com/spring-cloud/spring-cloud-gcp/pull/323#pullrequestreview-91551889

As I understand, this would pull in the `autoconfigure` module, along with maybe `spring-boot-starter`?

Still unclear what the what this starter will achieve that `autoconfigure` alone wouldn't.

@snicoll maybe you could add some colour here?

**Comment by meltsufin** [comment]
Is the idea to essentially merge `autoconfigure` into `spring-cloud-gcp-starter`?

**Comment by snicoll** [comment]
No. A starter has no code. 

It's more related to what @dsyer has proposed in his PR. Each starter brings the autoconfigure module manually. This represents the concept of "GCP support" that can be activated when adding more stuff to the classpath.

In practice, this represents my idea of "GCP Support" on start.Spring.io. That's how we could be smart by detecting user's decision. For instance GCP Support + JDBC + Mysql -> add the Mysql specific jar for GCP. GCP Support + Integration -> add the integration support for GCP, etc.

This entry is key for a number of features. Having a starter that represents that would be nice IMO.

**Comment by meltsufin** [comment]
@snicoll What if in specifying "GCP Support + Trace + JDBC + Mysql", the user wants to connect to a local MySQL, rather than Cloud SQL, but use Cloud Trace support? It's a bit ambiguous. Cloud SQL for MySQL requires a different JDBC driver than the regular MySQL.

**Comment by snicoll** [comment]
Oh well. That really is a problem.

**Comment by dsyer** [comment]
> Cloud SQL for MySQL requires a different JDBC driver than the regular MySQL.

We didn't know that because there was no example anywhere (and there still isn't). In fact, the only code I see in this repo used the regular MySQL connector (in the starter, as Stephane points out). Can you clarify what you mean a bit? What is the goal? Is it just a specific set of dependencies, or is it something that needs to be switched off locally, but on in production? Something to do with MySQL? What??

**Comment by meltsufin** [comment]
We have these two GCP-specific dependencies in the Cloud SQL starter:
```xml
		<dependency>
			<groupId>com.google.cloud.sql</groupId>
			<artifactId>mysql-socket-factory</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.cloud.sql</groupId>
			<artifactId>postgres-socket-factory</artifactId>
		</dependency>
```

So what I said was not actually completely accurate. We still use the basic mysql and postrges drivers, but they need to be augmented by these two dependencies.

It's still a problem though, because for Cloud SQL (MySQL) we want to automatically write the JDBC URL in autoconfig, which would not work for vanilla MySQL.

**Comment by snicoll** [comment]
> It's still a problem though, because for Cloud SQL (MySQL) we want to automatically write the JDBC URL in autoconfig, which would not work for vanilla MySQL.

I think we should take a step back and work with concrete samples. Adding `mysql-socket-factory` is a signal you want to use the Cloud SQL feature. Back you your example about trace and mysql, the user can just ditch that to get back to local mysql if that's what  they want. 

Also, I'd expect the auto-configuration here to afford for that use case. Relying only on the classpath is wrong, you should have a way to let the user express what they want.

**Comment by meltsufin** [comment]
I agree that adding `mysql-socket-factory` could be a signal to turn on autoconfiguration for Cloud SQL (MySQL). In fact, I think we're doing that already.

However, I don't think this point relates to the problem of ambiguous intent in the Initializr example:

GCP Support + Trace + JDBC + Mysql

Do you add dependencies for Cloud SQL here or not?

**Comment by snicoll** [comment]
Yes and my take on that is that asking for GCP support with Mysql may mean you want or don't want the cloud SQL feature. Perhaps that's something we can clarify in the way the auto-configuration works. If, as a user, I provide an explicit `spring.datasource.url` to my local Mysql database, the auto-configuration shouldn't mess with that. 

Considering it doesn't, I don't understand what  the problem is. If it does, I believe there is a problem, independently of the initializr use case we're discussing here.

**Comment by meltsufin** [comment]
That's an interesting resolution I haven't thought of for this example.
Is there a mechanism in Spring Boot auto-config to inspect a property for a particular pattern to detect that it's pointing to a local MySQL server?
