### ISSUE TITLE
Support object payload in PubSubTemplate

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#361]
A way to send an object and marshall w/ converter, e.g., send(topic, Object message) & use converter, potentially detect Jackson in classpath and automatically register a JSON converter.

Issue spun off from #92.

**Comment by ChengyuanZhao** [comment]
Perhaps we don't need to involve JSON and such @meltsufin.
It looks like the PubsubMessage type and its builder allows you to add Objects along with some java type information.  That implies  to me we should be doing something similar to what we do for Spanner, which is using Spring to create instances of the objects and then using reflection and the type information from the PubsubMessage and FiedDescriptors to set the properties.

**Comment by ChengyuanZhao** [comment]
@meltsufin It seems like it would be doable for RC1 to just serialize the object into the messages "data" as as bytes or a string. Do you have a preference for JSON or regular Java Serializeable? 

I have a preference for Java serialization at the moment for these reasons:
- we can have `<T extends Serializable> publish(final String topic, T payload)` and `<T> T getNext(String subscription)`. The usage here is that the user would have a specific subscription just for objects of that given type, so we can have `getNext` with a type parameter. 
-  the type constraint `extends Serializeable` is a good check for the user's code at compile time instead of run time
- because java serialization carries the type information, when deserializing we can just cast the result to `(T)`. On the otherhand, JSON serialization doesn't have the type information, so the user would need to provide a `Class` instance of their desired type in addition to providing the type param T.

**Comment by ChengyuanZhao** [comment]
@artembilan thank you for the links! I'll look into using the Jackson with some type information given the team's general preference for a JSON way to do this. I'll post later with some more details about how I'm gonna do this

**Comment by ChengyuanZhao** [comment]
The link describing enabling type information in Jackson also mentions some security considerations, but it isn't an issue if the sender and receiver of the typed "objects" are controlled by the same people, which I assumed is what we picture our users to be. does that sound good @meltsufin ?

```
1.1.1 Security Risks using Global default typing
Note that if you:

Enable use of global type information, using Class name as the type id AND
Accept content from untrusted sources
you may expose a security hole in case untrusted source manages to specify a class that is accessible through class loader and exposes set of methods and/or fields, access of which opens an actual security hole. Such classes are known as “deserialization gadget”s, and although Jackson contains a pre-defined black list for blocking known cases new ones are found over time so that at any given time there may be unblocked attack vectors.

Because of this, use of "default typing" is not encouraged in general, and in particular is recommended against if the source of content is not trusted. Conversely, default typing may be used for processing content in cases where both ends (sender and receiver) are controlled by same entity.
```

**Comment by artembilan** [comment]
Well, even though you may it treat like that, you shouldn't forget that we are developing here a Spring project. And it definitely has to fit any security vulnerabilities protection.
What we are talking about here is this: https://spring.io/blog/2017/06/08/cve-2017-4995-spring-security-4-2-3-released.

As a sample for the fix you can find here: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/support/json/JacksonJsonUtils.java#L99

**Comment by meltsufin** [comment]
@ChengyuanZhao I think JSON is the way to go. Regarding other details, I would defer to @joaoandremartins and @artembilan who are better experts on SI than me.

**Comment by artembilan** [comment]
Yes, I think you really can rely on that `JacksonJsonUtils` from Spring Integration. And right, you could expose such a `trusted.packages` configuration property. 

Not sure though in your other question. Will deffer that to Mike and João.
