### ISSUE TITLE
Add SubscriberConfiguration and PublisherConfiguration

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#363]
Spun off from #92.

@saturnism Please clarify what you meant by this.

**Comment by joaoandremartins** [comment]
I think the requirement here was to add all the little configurable bits from the Pub/Sub classes to a `@ConfigurationProperties` class that we would have to map manually.

I think the agreement was to abandon this idea and instead add any settings on demand, but @saturnism can let me know if I'm wrong.

**Comment by meltsufin** [comment]
Currently we autoconfigure `DefaultPublisherFactory` and `DefaultSubscriberFactory`. However, there are many different properties that can be set for each, which we are not setting. The idea is to expose more properties to be used in the autoconfiguration of these beans.

**Comment by meltsufin** [comment]
Retry settings come to mind. Maybe let's get a list and try to go from there?

**Comment by ChengyuanZhao** [comment]
- DefaultPublisherFactory
- - RetrySettings
- - - setTotalTimeout
- - - setInitialRetryDelay
- - - setRetryDelayMultiplier
- - - setMaxRetryDelay
- - - setMaxAttempts
- - - setJittered
- - - setInitialRpcTimeout
- - - setInitialRpcTimeout
- - - setInitialRpcTimeout
- - - setInitialRpcTimeout

**Comment by ChengyuanZhao** [comment]
@saturnism PTAL

**Comment by ChengyuanZhao** [comment]
Would it make more sense to just have the user provide their own beans for many of these settings instead of us putting them all the way through as spring boot config settings?

**Comment by meltsufin** [comment]
It looks like if we do flow control settings, retry settings, and batching settings, we got most of everything covered. Wherever a whole implementation is needed, we can skip those.

**Comment by ChengyuanZhao** [comment]
Which retry settings and flow control settings ? (Several of the sub-settings use those types)

This is part of the reason I am for having the user provide the instances of these objects instead of exposing all of the repeated underlying numbers/strings as properties settings.

**Comment by ChengyuanZhao** [comment]
@meltsufin What do you think? Instead of exposing so many individual values in properties files we can make bean functions that take in the entire retry setting and flow control setting objects for those various settings and rely on name-matching (with  `@Qualifier`) instead of type-matching (since there are several params of the same type).

**Comment by meltsufin** [comment]
I don' think those two things are mutually exclusive. The purpose of the properties is to provide settings for auto-configured beans. Overriding auto-configured beans with more flexibility is always an option.

**Comment by ChengyuanZhao** [comment]
I am not saying making the properties is not technically possible ,but only that it seems extremely user-unfriendly. Please confirm, you would like me to expose those thirty-something settings to the user?

**Comment by ChengyuanZhao** [comment]
I ask for clarification because this is a nice-to-have type of issue, and I would like to capture what the OP wanted out of this so I can go ahead and make the PR.

**Comment by meltsufin** [comment]
If you group the settings into reusable POJOs like `RetrySettingsProperties`, I think you should end up with much fewer than 30 actual instance variables.
I'm not saying that we should expose all of them, but only the ones that seem likely to be useful. I haven't done that analysis to tell you exactly which ones it would be.

**Comment by ChengyuanZhao** [comment]
Even if you group them into a properties object, you would still need to document each of them separately because to the user they still are literally thirty-something individual settings.

Regarding which ones to keep and that analysis, did you mean looking through each one and coming up with personal anecdotal opinions on which would be nice to keep? Or waiting for user feedback about what to make adjustable? 

After listing these out and seeing the pros and cons of it, I am feeling like P2 isn't appropriate for this, and this should be a post-GA/enhancement/back-burner labeled issue.

**Comment by meltsufin** [comment]
@ChengyuanZhao What do you think of splitting this into smaller issues? We can address exposing retry settings first and then handle the rest. It may be more manageable.

**Comment by meltsufin** [comment]
Regarding which parameters should be exposed, you can reach out to the Pub/Sub team and see what they would recommend.

**Comment by ChengyuanZhao** [comment]
@meltsufin I think splitting this one up wouldn't be a good idea. Once I have confirmation from the requesting parties (you, Ray, and anybody else who wants to chime in) about what you would all like to see, then  I can bang out the PR in an hour or two. 

I do not want to make this a bureaucratic process because it is a rather simple nice-to-have enhancement. I can reach out to the pubsub team, but because that is not going to be an urgent process, I will relabel this issue.

**Comment by meltsufin** [comment]
@ChengyuanZhao How about splitting this issue into "expose beans" (P2) and "expose properties" (P3).

**Comment by ChengyuanZhao** [comment]
To clarify why I don't think we should do both methods at the same time: 

If I place myself in the user's shoes then I think there are many questions that I would have: which method takes priority? what if I want to configure that priority? what if I want this priority at the setting level or even sub-setting level? what If I want to merge the settings from both methods at the sub-setting level? 

While potentially useful, I think supporting both ways opens up many ways for unnecessary complexity and bugs.

**Comment by ChengyuanZhao** [comment]
@meltsufin to confirm from discussion , we are adding all  properties and beans.

**Comment by meltsufin** [comment]
Yes.
