### ISSUE TITLE
Spring Cloud GCP Core Project ID not populated properly in Cloud Shell

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#415]
See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2855

In Cloud Shell, if project ID is not explicitly set in env var, it'll pick it up from the metadata server, results in `no-project-id`.

**Comment by ChengyuanZhao** [comment]
Hey Ray, could you explain more about this issue? From reading the other ticket it sounds like it's an issue with Cloud Shell? How is the Spring Cloud GCP project getting involved?

**Comment by meltsufin** [comment]
Would the fix for this be in [google-cloud-java](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2855)? We rely on `ServiceOptions.getDefaultProjectId()`.

Can you reproduce this issue, @ChengyuanZhao?

**Comment by ChengyuanZhao** [comment]
@meltsufin well I'm not clear yet on how to reproduce:  if I unset the project ID in my cloud SDK, don't provide the credentials file at GOOGLE_APPLICATION_CREDENTIALS, and don't set GOOGLE_CLOUD_PROJECT, then I indeed get no-project-id error in any of our spring cloud gcp samples, but isn't that expected?  I just am not clear on how Cloud Shell fits into the picture.

**Comment by joaoandremartins** [comment]
I think the issue is when you set the project ID with the Cloud SDK.
AFAIU the `GOOGLE_CLOUD_PROJECT` envvar is set, but `ServiceOptions.getDefaultProjectId()` always returns `no-project-id` from the metadata server.
It didn't use to be that way on earlier versions of google-cloud-java, though, which is why this became an issue.

It sounds like we would need to also check for the `GOOGLE_CLOUD_PROJECT` envvar on our side before falling back to `ServiceOptions`. This could be done in `GcpContextAutoConfiguration`, for example.

**Comment by ChengyuanZhao** [comment]
Since this issue is already known to google-cloud-java (as we see from the linked ticket), why don't we let them make the fix? Seems logical

**Comment by saturnism** [comment]
Sorry this was original tracking in case someone else runs into the issue from the Spring Cloud GCP. 

They've fixed the issue from Cloud Shell. Thanks!
