### ISSUE TITLE
Remove Google Cloud Java BOM import from our BOM

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#456]
@joaoandremartins The best practice seems to be to not include external dependnecies in the BOM, but rather keep them in the parent POM.
We seem to violate this rule in our BOM by importing the Google Cloud Java BOM there.
Also see: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2781

**Comment by snicoll** [comment]
Actually if the Google Cloud Java BOM complies with that rule (and it looks like it does now), I am keen to actually keep using it because if you don't provide it, the user will have to do that.

This BOM is providing support for the Google platform and, as such, should provide versions for Google-related artifacts.

**Comment by snicoll** [comment]
I've created #471 - We need to figure out if Guava is used by production code as well because if the version has to be set by the project, user's projects will be affected too.

I've seen it failing with a test only so maybe a local override is enough. If not, we need to add guava as an explicit dependency so that Maven chooses the shortest path.

**Comment by joaoandremartins** [comment]
@snicoll the proposal here is to use `google-cloud-java`'s BOM internally, through the root `pom.xml`, rather than put it in the BOM.
This way, users don't need add the BOM to their pom.xml.

We're also [setting a version for guava in the root `pom.xml`](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/pom.xml#L78).

@meltsufin should we move on with this for M3?

**Comment by meltsufin** [comment]
Yes, I'll close.
