### ISSUE TITLE
Add support for Google Cloud Bigtable

### ISSUE THREAD

**Issue by mbrukman** [spring-cloud/spring-cloud-gcp#486]
A request was made on [Stack Overflow][1] for this integration to enable easier development with Spring and Bigtable.

[1]: https://stackoverflow.com/questions/49290261/integration-of-spring-and-bigtable-database

**Comment by joaoandremartins** [comment]
Thanks for the request, @mbrukman.
We actually heard this request before, from @sduskis.
We ultimately decided to not pursue the integration, since `spring-hadoop`, the project we thought made more sense to integrate with, hasn't been that active and is [still using old HBase versions](https://github.com/spring-projects/spring-hadoop/blob/master/gradle.properties) (pre HBase 1.0).

I'm going to go ahead and close this issue, but please feel free to reach out if you think there's anything else we could do for Bigtable users on Spring.

**Comment by dhoard** [comment]
@joaoandremartins I can see a lot of value in having interfaces / "Templates" `BigtableAdminOperations` / `BigtableAdminTemplate` and `BigtableOperations` / `BigtableTemplate`.

This seems like a natural fit for a future release of `spring-cloud-gcp` and would provide for common Bigtable use cases.

For reference to issue watchers, Spring for Apache Hadoop project will reach End-Of-Life status on April 5th, 2019 (https://spring.io/projects/spring-hadoop)

**Comment by meltsufin** [comment]
@dhoard Thanks for the feedback. We'll definitely consider it as we plan future work on the project.
