### ISSUE TITLE
Inconsistent version of Guava

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#582]
I was concerned with the way the [guava version is handled in this build](https://github.com/spring-cloud/spring-cloud-gcp/pull/466#issuecomment-373566292) that got no answer

A fresh project created with only `spring-cloud-gcp-starter` on start.spring.io brings `com.google.guava:guava:jar:18.0`

[This line is useless](https://github.com/spring-cloud/spring-cloud-gcp/blob/5dab9f4f3375118b153c04cadd8e38fb379b6551/pom.xml#L81) if you're not using guava yourself as it will fix the version for your build internally but will not promote the fact you have a preference for that version. For that to happen, you have to add a dependency explicitly on guava (which is quite messy if you ask me). Adding that to  `spring-cloud-gcp-core` might do what you want.

Guava is known to be very problematic so perhaps we should reconsider its usage?

**Comment by joaoandremartins** [comment]
We set guava's version only internally on purpose. The idea was that our project shouldn't promote versions of dependencies that it doesn't manage. Setting the version in our BOM is a can of worms, because other BOMs might take precedence in the dep graph, and our version is not guaranteed to be the final one.

We're almost barely using guava in our project (only some `ImmutableMap` here and there). We actually don't care which guava version is used. The only reason we're setting the version of guava is because `spring-cloud-dependencies` sets the version to 18, which breaks our dependencies that use guava.

Let me know if you have other questions.

**Comment by meltsufin** [comment]
Note that the Guava dependency is coming from `com.google.cloud:google-cloud-core`, which we need in the core starter. I think the client libraries team recognizes that versions of Guava are often very problematic and they were going to shade their usage of Guava, but I'm not sure if it has happened yet.
@garrettjonesgoogle

**Comment by snicoll** [comment]
> We set guava's version only internally on purpose

Well your build and your tests are executed with a different version as the one that is used by default by any app so, IMO, that's what is asking for troubles.

I know that this project doesn't use guava but other google-related artifacts do and your build overrides the guava version. You either have to mark that preference (as indicated in my original comment) or you should remove that override.

Please note that I never mentioned the BOM and, indeed, let's not even mention that.

**Comment by meltsufin** [comment]
+1
I guess we override the version because the build fails otherwise. :smile: 
Let's find a better solution like @snicoll suggests.

**Comment by joaoandremartins** [comment]
We had to set guava's version to 20 because google-cloud-java uses guava features higher than 18 and apps break at runtime.

Assuming every project follows the best practice of not promoting versions of dependencies they don't manage, the best fix would probably be to exclude the troublesome BOM, `spring-cloud-starter-netflix-archaius`. If that works, it would allow us to not set any version for guava at all. This would work, assuming that no one in Spring Boot or Spring Cloud repeats the same mistake of publishing guava's version in a BOM again.

**Comment by snicoll** [comment]
`spring-cloud-starter-netflix-archaius` is not a BOM. Can you please add a link to the BOM that sets the version of Guava?

(I am not sure I agree with the rest of your comment but let's figure this one first please).

**Comment by joaoandremartins** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-dependencies/pom.xml#L422

Unfortunately, the latest version of `google-cloud-java` requires a guava version higher than 18 otherwise the build fails. So any solution here will have to involve a fix to this BOM.

**Comment by meltsufin** [comment]
@garrettjonesgoogle That's one option, but what about shading Guava in Google Cloud Java libs?

**Comment by joaoandremartins** [comment]
Opened https://github.com/spring-cloud/spring-cloud-netflix/issues/2854 to remove the guava version from the dependency management.

**Comment by garrettjonesgoogle** [comment]
@meltsufin That would bloat binary size for cases like Android, and it creates a lot of problems to release two variants of a library, one of which shades & one of which doesn't.
