### ISSUE TITLE
Spanner CDI integration

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#590]
Implement CDI compatibility layer for Spring Data Spanner. 
Starting point: [Spring Data MongoDB CDI support](https://github.com/spring-projects/spring-data-mongodb/tree/3012bcd575d85ad7cd11e07962fc168d4bbc98b2/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/cdi)

**Comment by meltsufin** [comment]
@mp911de Is CDI support widely used in Spring Data?

**Comment by mp911de** [comment]
That’s not a simple yes/no answer. There’s little support for Spring Data-like tools in the CDI space. The only comparable library is DeltaSpike that provides repository support for JPA. With EE servers, Spring Data usage was quite popular because of the obvious benefits. Nowadays, with a movement towards lightweight stacks, I don’t have a clue where all this is going. It makes sense for consistency reasons, on the other side, Spring Cloud GCP is tied much more to Spring Boot than Spring Data.

**Comment by meltsufin** [comment]
Thank, Mark. We're indeed very much tied to Spring Boot. Based on your comment and the lack of any expressed interest from actual users, closing it.
