### ISSUE TITLE
Spring Boot apps using Pubsub channel adapters hang on shutdown

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#60]
I noticed this happens when terminating my toy app. I suspect the delays are taking place at resource cleanup, more specifically, terminating connections to Google Cloud Pub/Sub.

Just leaving it here for future reference. We would want to get to the bottom of it before any alpha release.

**Comment by artembilan** [comment]
First of all would be great to have some thread dump to see who and where is blocked.
OTOH I see this:
```
 * // Wait for a stop signal.
   * done.get();
   * subscriber.stopAsync().awaitTerminated();
   * }</pre>
   */
  @Override
  public ApiService startAsync() {
```
meanwhile we have only this code:
```
protected void doStop() {
	if (this.subscriber != null) {
		this.subscriber.stopAsync();
	}
```

So, we don't wait for the termination and just go ahead to the application context close. Since that async stuff isn't terminated yet, Tomcat treats that as a leak. 

Just my feeling.

**Comment by joaoandremartins** [comment]
Haven't experienced this in a long time, closing for the time being.
