### ISSUE TITLE
UsageTrackingHeaderProvider determines wrong project version

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#630]
This may be caused by `getClass().getPackage().getImplementationVersion()` not working correctly when the project jars are repackaged. We should find an alternative way of capturing the version. Perhaps by writing it to a file during the Maven build.

**Comment by ChengyuanZhao** [comment]
@meltsufin 

I'm thinking we could just have a java constant string for the version and then a unit test that checks

1. if `getClass().getPackage().getImplementationVersion()` says "SNAPSHOT" then pass.
2. otherwise, if the java constant string doesn't match `getClass().getPackage().getImplementationVersion()` then fail. this way we'll not forget to update this string when we do real releases.

**Comment by meltsufin** [comment]
It's a good idea to have a test like that. However, I would rather have the version constant updated automatically during the build. Maven resource filtering can probably be used for this.

**Comment by ChengyuanZhao** [comment]
I'll take this one and use the resource filtering then

**Comment by ChengyuanZhao** [comment]
@meltsufin Do you want to stick with properties files or potentially write the version into the java files automatically? Note that i don't think resource filtering will work for the java file approach, and it could be more complicated.

**Comment by meltsufin** [comment]
@ChengyuanZhao I'm now thinking just hard-coding the version in code. We can later optimize it by auto-generating the source file.

**Comment by ChengyuanZhao** [comment]
We would lose the (potential) per-module version differences then, right ? And both components in that header would always be the same then ?

**Comment by meltsufin** [comment]
Right, but frankly, I'm not too concerned about the per-module version tracking, we can even leave it as `this.clazz.getPackage().getImplementationVersion()`, or add an assertion that `this.clazz.getPackage().getImplementationVersion()` == <hard coded version>.

**Comment by joaoandremartins** [comment]
FYI our metrics use the per-module version. The one from `Spring/1.0.0.whatever` is currently unused.

**Comment by ChengyuanZhao** [comment]
Do you mean adding that assertion in `UsageTrackingHeaderProvider` ? Wouldn't that crash the user's program if he had rebuilt it and his own strange version was there?  In that case shouldn't we use the hard-coded-version, and just have a unit test on our side for our builds to make sure that the hard-coded version isn't outdated?

**Comment by meltsufin** [comment]
@joaoandremartins Thanks for pointing that out! In that case we should definitely have tests verifying the version match in each tracked module.

**Comment by ChengyuanZhao** [comment]
@meltsufin to confirm, we want what I described at the very top of this thread, but for each module. right?

**Comment by meltsufin** [comment]
@ChengyuanZhao Disregard my comment about the assertion. It doesn't really make sense. Unit tests can also be problematic when someone forks and changes the version. I'm leaning towards just using the same root version for every module. That way you don't have to hard-code it in multiple places. It's currently unlikely that we will have different module versions across the project.

**Comment by ChengyuanZhao** [comment]
I'm ok with that. However, wouldn't a mechanism to prevent us from forgetting to update this hard-coded java string be valuable and worth the potential cost of somebody forking this having to also update that test ? The cost of forgetting to update that string could be high, because if we release without updating it then we may taint much of our metrics results from ppl who grabbed the new release but still using the old version string.
