### ISSUE TITLE
Provide ACK control

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#8]
Spring Messaging in general has the notion of a MessageListenerContainer, which allows configuration of different settings such as ACK mode, concurrent listeners.

We need to add same behavior here not only to be consistent with the Spring ecosystem, but to allow our users to control those parameters.

As usual, let's use the spring-kafka project (https://github.com/spring-projects/spring-kafka/tree/master/spring-kafka/src/main/java/org/springframework/kafka/listener) as source of inspiration, since it's a new take on a well stablished concept

**Comment by artembilan** [comment]
The AWS `KinesisMessageDrivenChannelAdapter` (https://github.com/spring-projects/spring-integration-aws/tree/master/src/main/java/org/springframework/integration/aws/inbound/kinesis) is another (new) sample with similar approach and it isn't based on the `MessageListenerContainer` pattern. 

Just in case to gather as much as possible info for consideration...

**Comment by joaoandremartins** [comment]
@artembilan I looked into that Kinesis example, but couldn't find anywhere where (n)acking is done.

Did you mean we can do something similar to how the checkpointing is done there?

In any case, sounds like a start would be to add a new header to specify auto/manual acking and then `PubSubInboundChannelAdapter` could either ack messages after `sendMessage()` or else send the `AckReplyConsumer` back to the user, although we would probably want to replace that with something Spring and not part of the Google Cloud Pub/Sub API.

**Comment by artembilan** [comment]
The Apache Kafka and AWS Kinesis are `offset`-based. To track what we have processed we need to `acknowledge`  somehow our work. Apache Kafka suggests `Consumer.commit()` API on the matter.
Since `Consumer` is very low and critical API to expose for end-user in case of message handling, we have introduced more high level `Acknowledgment` contract which we supply in message headers - `KafkaHeaders.ACKNOWLEDGMENT`. That is already end-user responsibility to perform that `acknowledge()` hook whenever it is convenient for him/her and `ackMode` is `MANUAL`.

Unlike Apache Kafka, AWS Kinesis doesn't provide the `sequenceNumber` tracking mechanis, a-la `commit`. Anyway we would like to do that from our side for better user experience. That's how we introduce that `checkpointStore` abstraction and, therefore, `Checkpointer` contract, which is fully equal to that Spring Kafka `Acknowledgment`.

Since GCP PubSub provides already one stop shop `AckReplyConsumer` pretty high level API, I don't see reason to overcomplicate end-user experience and just provide this object into the header like we do right now - `messageHeaders.put(GcpHeaders.ACKNOWLEDGEMENT, consumer);`.

Only what we need to do here is `ackMode` to let the `PubSubInboundChannelAdapter` (n)ack messages automatically after receiving or delegate into via headers to end-user.

As said in other place: we are fully fine with an existing API if that is fully sufficient for the dependency injection and in this case for the messaging.

In fact for similar MANUAL ack we expose AMQP `Channel` directly to end-user via headers in the SI-AMQP module:
```
if (AmqpInboundChannelAdapter.this.messageListenerContainer.getAcknowledgeMode()
				== AcknowledgeMode.MANUAL) {
	headers.put(AmqpHeaders.DELIVERY_TAG, message.getMessageProperties().getDeliveryTag());
	headers.put(AmqpHeaders.CHANNEL, channel);
}
```

**Comment by joaoandremartins** [comment]
One worry I usually have when opting for platform-specific APIs instead of Spring abstractions is code portability. One of the biggest Spring advantages to me is that, in this case, I could go from another provider to GCP (or vice-versa) to use messaging just by swapping out some low-level components (e.g., channel adapters).

Adopting these GCP API bits could be harmful for lock-in. Although if you're OK with it, I guess it's fine!

**Comment by artembilan** [comment]
> I could go from another provider to GCP (or vice-versa)

But you should agree with me that in real life we hardly ever do that. And if that happens, there are a lot of other code which requires changes because fully different provider.

Well, and that for what Spring Cloud Stream with its binder abstraction is aimed - to let to switch (or mix) Microservices communication via messaging.
