### ISSUE TITLE
Use org.springframework.data.annotation.* wherever possible

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#904]
This means replacing `@NotMapped` with `@Transient`, and `@Embedded` with `@Reference`.

**Comment by ChengyuanZhao** [comment]
I think we need to keep `@Embedded` but we can indeed replace `@Reference`. 

The reason is embedded POJOs don't need to be annotated with `@Entity` because they don't have their own Kind, so there isn't a good way to distinguish a POJO that is supposed to be embedded vs one that is supposed to just be converted using custom converters.
