### ISSUE TITLE
Declarative transactions with @Transactional in Datastore

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#905]

**Comment by ChengyuanZhao** [comment]
https://cloud.google.com/datastore/docs/concepts/transactions

Cloud Datastore also offers explicit `commit` and `rollback`, so we can implement a `DatastoreTransactionManager` that takes advantage of Spring Data AOP support similar to how it is being done in #1001

**Comment by ChengyuanZhao** [comment]
As I mentioned in #996, transactions can only act on the children of a given entity and they all must be connected eventually to that root entity via ancestor relationships. This makes sense when you think about it since we've long read in the docs that the only way to do transactions is with an ancestor. This is the primary benefit of the ancestor feature, I think.

Anyways, I'm putting on the awaiting tag until we have implemented the ancestor feature. @meltsufin @dmitry-s @saturnism  FYI

**Comment by ChengyuanZhao** [comment]
We will be using cross-group transactions, so we can touch up to 25 entity groups. 

It does not seem like this `@Transactional` work needs to be aware of the the ancestor relationships so removing the awaiting label.
