### ISSUE TITLE
Save entity which has children which internally might have several children

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#907]
Looking for a mechanism to save entities which will have child objects

Say an entity X has List<X1> , List<X2> , List<x3>
and X1 internally has List<Y1> , List<Y2>

how we persist the entities using spannerOperations ?

Currenlty we are making multiple insert calls to insert one entity. 

INSERT(ENTITYX)
Foreach(x1) -> insert(x1)->for each y1 (insert y1)
                                          ->for each y2 (insert y2)
Foreach(x2)-> insert(x2)
foeach(x3)->insert(x3)

**Comment by vineela-gampa** [comment]
@ChengyuanZhao We used STRUCT to retrieve data currently till @oneToMany annotation is implemented. How can this be done using STRUCT ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa 
Doing this saving for a family tree of objects like this in a single call will need to wait until I have implemented according to #853. The reason is that Cloud Spanner only allows writes to be done via individual mutations that are per-row-per-table. While these mutations can be submitted in batch, generating each of them I think will need to be done recursively as is the plan in #853. Until then the only way I can think of is what you mentioned (iterating through yourself and saving each).

STRUCTs can't be saved into columns, so the mapping of nested STRUCTs to nested objects is only one-way in the read direction.

**Comment by ChengyuanZhao** [comment]
I'm going to close this as #853 is the up-to-date issue for tracking the parent-child interleaved work.
