### ISSUE TITLE
Updates docs not to recommend `gcloud auth application-default`

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#968]
Using service accounts instead is recommended.

**Comment by meltsufin** [comment]
In our sample apps the [link](https://developers.google.com/identity/protocols/application-default-credentials) to application default credentials docs is actually broken.

**Comment by meltsufin** [comment]
@saturnism What's the current recommendation on default credentials usage?

**Comment by ttomsu** [comment]
I'm not sure why this isn't recommended. Perhaps because the user may have different authorizations than the service account it will run under? 

If that is the case, then we should recommend activating a service account and letting the client libraries automatically find this credential - https://cloud.google.com/sdk/docs/authorizing#authorizing_with_a_service_account

**Comment by meltsufin** [comment]
Service account is the alternative, AFAIK. Some APIs don't even support application-default creds. I'm still not sure what is the current recommendation.

**Comment by meltsufin** [comment]
I consulted the Cloud SDK team and application-default creds are still recommended for services that support them.
