### ISSUE TITLE
Automatic grouping of Pub/Sub messages by subscription name when acking

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#975]
Using `ack()`, `nack()`, and `modifyAckDeadline()` methods for acknowledging messages in batches is more efficient than acknowledging messages individually, but they *require* the collection of messages to be from the same project and subscription. This restriction can be lifted by automatically grouping messages by subscription name and processing those batches separately.

The feature was originally there, but removed in #859 when converting to asynchronous acknowledgement.

**Comment by dhoard** [comment]
@meltsufin Since subscription names are only unique within a project, I don't understand how this could be implemented.  That's why I am grouping based on `ProjectSubscriptionName`

What am I missing?

given ...

message A from a subscription named "test-subscription" via `PubSubSubscriber` A / credentials A in project A.

message B from subscription named "test-subscription" via `PubSubSubscriber` B / credentials B in project B.

then ...

both have the same subscription name (`test-subscription`), but because they are from different projects, they can't necessarily be grouped together.


Also, in this scenario ...

message B can't be acknowledged by `PubSubSubscriber` A

message A can't be acknowledged by `PubSubSubscriber` B


If `PubSubSubscriber` A and B are both using the same credentials, then it would be possible for either `PubSubSubscriber` (A or B) to acknowledge the message.

**Comment by meltsufin** [comment]
I forgot to mention that all messages still have to be from the same project, but not necessarily from the same subscription. Does that make sense?

**Comment by meltsufin** [comment]
This would indeed be a problem, but I would consider it to be a user error because it would mean that those message came from different Pub/Sub templates, yet being submitted together for acking to one of the templates.

That being said, if I'm the only one who thinks this would be useful, I willing to drop this feature. 😄

**Comment by dhoard** [comment]
I would be interested in other people's thoughts. @dmitry-s @artembilan @ChengyuanZhao

**Comment by artembilan** [comment]
> message B can't be acknowledged by PubSubSubscriber A

Can you confirm this with your experience or test case?
If that really fail with an error, we are good just document restrictions and left everything else up to end-user to group messages properly.
Well, i mean we still can group them automatically here in the template: the way @meltsufin suggests, but fail if there is wrong subscription.

We still fail here with the:
```
Assert.isTrue(
					projectSubscriptionName.equals(acknowledgeablePubsubMessage.getProjectSubscriptionName()),
					"The project id and subscription of all messages must match.");
```
So, that won't hurt too much if we are going to fail against some other condition.

Summarizing this: +1 from me to go ahead with grouping by subscription and let it to fail naturally.
If that is possible, of course, with the fact of async confirmation/rejection for each group...

**Comment by elefeint** [comment]
To make sure I understand the different scenarios:
1) messages from the same project, with the same credentials and from the same subscription -> ack all at once.
2) messages from the same project, from N different subscriptions -> ack in N batches.
3) messages from the same project, with at least one subscription having incorrect credentials -> attempt to ack in N batches; allow the bad-credentials subscription's batch to fail naturally
4) messages from different projects -> fail before grouping

Does this sound right?

**Comment by elefeint** [comment]
Duplicating an offline conversation on here for posterity.

First, an example: let's say you want to ack messages from 2 different subscriptions: slowSub and fastSub, where the second one acks a lot faster than the first, as the names indicate. If you have downstream operations and care about performance, you'd want to know about fastSub acking completion first -- that's the whole reason for getting ack results back asynchronously. So, the natural thing for PubSubSubscriberOperations to do would be to return a collection of ListenableFutures* where each one represents a single-subscription batch.

But! The API that emerged out of [async support PR ](https://github.com/spring-cloud/spring-cloud-gcp/pull/859) returns a single ListenableFuture:
ListenableFuture<Void> ack(Collection<AcknowledgeablePubsubMessage> acknowledgeablePubsubMessages);

This return type would be compatible with any other ListenableFuture, but not with a collection.

I see several options here:

1) Leave current ack/nack/modifyAckDeadline alone, and introduce a new set of methods ackMultipleSubscriptions, nackMultipleSubscriptions, modifyAckDeadlineMultipleSubscriptions that return a Collection<ListenableFuture> (assume better naming).
Upside: likely simplest solution that does supports requirements and does not break anything.
Downside: pollutes the API with extra methods.

2) Return a single ListenableFuture<Collection> by creating a custom ListenableFuture that keeps track of all per-batch futures and implements the interface accordingly.
Upside: completely backwards-compatible and in line with what was discussed on the original PR.
Downside: defeats the purpose of the speedup provided by asynchronicity -- all batches will have to wait for the slowest batch before invoking clients' success callbacks.
Both upside and downside: probably hell to code correctly. But "hell to code correctly" sounds like fun, so ¯\_(ツ)_/¯

3) Return an ugly, but compatible, wrapper like ListenableFuture<Collection<ListenableFuture>>>
Upside: supports requirements, does not break anything.
Downside: adds an extra ListenableFuture wrapper that is confusing and functionally unnecessary, existing only for backwards compatibility for something that existed for only a few weeks.

4) [likely not really an option for a public API, but leaving it here for completeness] Change the return type on existing methods and let users relying on M2 fix broken code.
Upside: simplest overall
Downside: breaks early adopters. I don't particularly want to anger early adopters.



* out of scope for this question, but I've made AckBatchStatus class to encapsulate all the useful data containing ProjectSubscriptionName, success status, exception object if applicable. So, the actual return would be ListenableFuture<Collection<AckBatchStatus>>.




------------------
From @meltsufin:
leaning to Option #2 because there are some mitigating factors:
(1) The client always has the option to compose the batch with only messages from a single subscription. (They actually have to do extra work to get messages from multiple subscriptions into a single collection because none of the API methods give you that.)
(2) The assumption that some subscriptions have significantly faster acking than others may not actually be true. We might want to ask the Pub/Sub team about that.
(3) Most users will deal with one subscription in their app, especially if it's a microservice.

**Comment by elefeint** [comment]
#1055 in its current state went back to returning ListenableFuture<Void> to indicate overall success or failure. The end user can submit individual per-subscription batches if per-subscription status is needed.
