### ISSUE TITLE
Support querying for BaseEntity or ProjectionEntity in DatastoreTemplate

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#995]
Currently we're not supporting projection queries (`ProjectionEntity`) at all in Datastore via the template or data repositories.

**Comment by ChengyuanZhao** [comment]
@meltsufin @dmitry-s 

I took a closer look and realized why we originally chose Entity instead of BaseEntity or ProjectionEntity:
Only Entity and FullEntity are supported for both reads and writes, and we decided on a converter structure that is based on the same source and sink type: Entity. This common type for source and sink is what other document-based Spring Data implementations do, so we felt it was most natural to also do this.

If we wanted to use BaseEntity or ProjectionEntity for reads then I think we have 2 options:

1. we need to have separate reader and writer converter classes  because the source and sink type are separate . this could make the code messier and harder to read. We also cannot implement the converter interface from Spring Data that extends both reader and writer and adds some more methods. 

2. we can make a proxy-like class maybe called StoreableEntity that internally holds Entity/FullEntity and a ProjectionEntity to satisfy both source and sink operations. However this feels more like a hack 

What do you guys think?

**Comment by ChengyuanZhao** [comment]
My mistake there, I added an EDIT line to my original comment: I thought we were still implementing EntityConverter from Spring Data, but saw we were already implementing EntityReader and EntityWriter separately.

**Comment by ChengyuanZhao** [comment]
awaiting #1002 . These two issues touch pretty much the same code.

**Comment by ChengyuanZhao** [comment]
@meltsufin @dmitry-s 

I was 100% done implementing this before integration tests failed and tipped me off to some debilitating limitations: https://cloud.google.com/datastore/docs/concepts/queries#limitations_on_projections

I don't think projection queries can be used. 

These limitations in that link alone i think make it not usable:
- Only indexed properties can be projected. So you cannot select  any properties that are unindexed. This completely defeats the purpose of the `@Unindexed` annotation that we added
- Properties referenced in an equality filter cannot be projected. Since we only plan to filter based on properties of the POJO using equality or otherwise, and we need to read those same properties to build the POJO... this means it's impossible
- Projection is not supported for strings that are longer than 1500 bytes, byte arrays that have more than 1500 elements, and other properties explicitly marked as unindexed. This size limitation is debilitating.

**Comment by meltsufin** [comment]
> * Only indexed properties can be projected. So you cannot select  any properties that are unindexed. This completely defeats the purpose of the `@Unindexed` annotation that we added

We can fail in this situation where the property is not indexed.

> * Properties referenced in an equality filter cannot be projected. Since we only plan to filter based on properties of the POJO using equality or otherwise, and we need to read those same properties to build the POJO... this means it's impossible

Why is it impossible? If it's an equality filter, then you already know what the column value is in the result set -- you don't need to include it in the projection. It is more logic though.

> * Projection is not supported for strings that are longer than 1500 bytes, byte arrays that have more than 1500 elements, and other properties explicitly marked as unindexed. This size limitation is debilitating.

Again, leave it up to the user to comply with this limitation and fail on our side.

I think generally, we probably want to support both via something like a flag "useProjections".
